package com.github.zackwoo.scaffolding.mapper;

import com.github.zackwoo.scaffolding.entity.Bannerdata;
import com.github.zackwoo.scaffolding.entity.BannerdataExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BannerdataMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BANNERDATA
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    long countByExample(BannerdataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BANNERDATA
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    int deleteByExample(BannerdataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BANNERDATA
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    int deleteByPrimaryKey(String favcategory);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BANNERDATA
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    int insert(Bannerdata record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BANNERDATA
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    int insertSelective(Bannerdata record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BANNERDATA
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    List<Bannerdata> selectByExample(BannerdataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BANNERDATA
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    Bannerdata selectByPrimaryKey(String favcategory);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BANNERDATA
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    int updateByExampleSelective(@Param("record") Bannerdata record, @Param("example") BannerdataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BANNERDATA
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    int updateByExample(@Param("record") Bannerdata record, @Param("example") BannerdataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BANNERDATA
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    int updateByPrimaryKeySelective(Bannerdata record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BANNERDATA
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    int updateByPrimaryKey(Bannerdata record);
}