package com.github.zackwoo.scaffolding.mapper;

import com.github.zackwoo.scaffolding.entity.Countrylanguage;
import com.github.zackwoo.scaffolding.entity.CountrylanguageExample;
import com.github.zackwoo.scaffolding.entity.CountrylanguageKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CountrylanguageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COUNTRYLANGUAGE
     *
     * @mbg.generated Tue Apr 11 16:12:16 CST 2017
     */
    long countByExample(CountrylanguageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COUNTRYLANGUAGE
     *
     * @mbg.generated Tue Apr 11 16:12:16 CST 2017
     */
    int deleteByExample(CountrylanguageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COUNTRYLANGUAGE
     *
     * @mbg.generated Tue Apr 11 16:12:16 CST 2017
     */
    int deleteByPrimaryKey(CountrylanguageKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COUNTRYLANGUAGE
     *
     * @mbg.generated Tue Apr 11 16:12:16 CST 2017
     */
    int insert(Countrylanguage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COUNTRYLANGUAGE
     *
     * @mbg.generated Tue Apr 11 16:12:16 CST 2017
     */
    int insertSelective(Countrylanguage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COUNTRYLANGUAGE
     *
     * @mbg.generated Tue Apr 11 16:12:16 CST 2017
     */
    List<Countrylanguage> selectByExample(CountrylanguageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COUNTRYLANGUAGE
     *
     * @mbg.generated Tue Apr 11 16:12:16 CST 2017
     */
    Countrylanguage selectByPrimaryKey(CountrylanguageKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COUNTRYLANGUAGE
     *
     * @mbg.generated Tue Apr 11 16:12:16 CST 2017
     */
    int updateByExampleSelective(@Param("record") Countrylanguage record, @Param("example") CountrylanguageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COUNTRYLANGUAGE
     *
     * @mbg.generated Tue Apr 11 16:12:16 CST 2017
     */
    int updateByExample(@Param("record") Countrylanguage record, @Param("example") CountrylanguageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COUNTRYLANGUAGE
     *
     * @mbg.generated Tue Apr 11 16:12:16 CST 2017
     */
    int updateByPrimaryKeySelective(Countrylanguage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COUNTRYLANGUAGE
     *
     * @mbg.generated Tue Apr 11 16:12:16 CST 2017
     */
    int updateByPrimaryKey(Countrylanguage record);
}