package com.github.zackwoo.scaffolding.mapper;

import com.github.zackwoo.scaffolding.entity.Lineitem;
import com.github.zackwoo.scaffolding.entity.LineitemExample;
import com.github.zackwoo.scaffolding.entity.LineitemKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LineitemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LINEITEM
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    long countByExample(LineitemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LINEITEM
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    int deleteByExample(LineitemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LINEITEM
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    int deleteByPrimaryKey(LineitemKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LINEITEM
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    int insert(Lineitem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LINEITEM
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    int insertSelective(Lineitem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LINEITEM
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    List<Lineitem> selectByExample(LineitemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LINEITEM
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    Lineitem selectByPrimaryKey(LineitemKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LINEITEM
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    int updateByExampleSelective(@Param("record") Lineitem record, @Param("example") LineitemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LINEITEM
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    int updateByExample(@Param("record") Lineitem record, @Param("example") LineitemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LINEITEM
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    int updateByPrimaryKeySelective(Lineitem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LINEITEM
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    int updateByPrimaryKey(Lineitem record);
}