package com.github.zackwoo.scaffolding.mapper;

import com.github.zackwoo.scaffolding.entity.Orderstatus;
import com.github.zackwoo.scaffolding.entity.OrderstatusExample;
import com.github.zackwoo.scaffolding.entity.OrderstatusKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OrderstatusMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORDERSTATUS
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    long countByExample(OrderstatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORDERSTATUS
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    int deleteByExample(OrderstatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORDERSTATUS
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    int deleteByPrimaryKey(OrderstatusKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORDERSTATUS
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    int insert(Orderstatus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORDERSTATUS
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    int insertSelective(Orderstatus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORDERSTATUS
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    List<Orderstatus> selectByExample(OrderstatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORDERSTATUS
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    Orderstatus selectByPrimaryKey(OrderstatusKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORDERSTATUS
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    int updateByExampleSelective(@Param("record") Orderstatus record, @Param("example") OrderstatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORDERSTATUS
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    int updateByExample(@Param("record") Orderstatus record, @Param("example") OrderstatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORDERSTATUS
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    int updateByPrimaryKeySelective(Orderstatus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORDERSTATUS
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    int updateByPrimaryKey(Orderstatus record);
}