package com.github.zackwoo.scaffolding.mapper;

import com.github.zackwoo.scaffolding.entity.Profile;
import com.github.zackwoo.scaffolding.entity.ProfileExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ProfileMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PROFILE
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    long countByExample(ProfileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PROFILE
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    int deleteByExample(ProfileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PROFILE
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    int deleteByPrimaryKey(String userid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PROFILE
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    int insert(Profile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PROFILE
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    int insertSelective(Profile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PROFILE
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    List<Profile> selectByExample(ProfileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PROFILE
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    Profile selectByPrimaryKey(String userid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PROFILE
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    int updateByExampleSelective(@Param("record") Profile record, @Param("example") ProfileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PROFILE
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    int updateByExample(@Param("record") Profile record, @Param("example") ProfileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PROFILE
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    int updateByPrimaryKeySelective(Profile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PROFILE
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    int updateByPrimaryKey(Profile record);
}