package com.github.zackwoo.scaffolding.mapper;

import com.github.zackwoo.scaffolding.entity.Sequence;
import com.github.zackwoo.scaffolding.entity.SequenceExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SequenceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SEQUENCE
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    long countByExample(SequenceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SEQUENCE
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    int deleteByExample(SequenceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SEQUENCE
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    int deleteByPrimaryKey(String name);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SEQUENCE
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    int insert(Sequence record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SEQUENCE
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    int insertSelective(Sequence record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SEQUENCE
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    List<Sequence> selectByExample(SequenceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SEQUENCE
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    Sequence selectByPrimaryKey(String name);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SEQUENCE
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    int updateByExampleSelective(@Param("record") Sequence record, @Param("example") SequenceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SEQUENCE
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    int updateByExample(@Param("record") Sequence record, @Param("example") SequenceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SEQUENCE
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    int updateByPrimaryKeySelective(Sequence record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SEQUENCE
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    int updateByPrimaryKey(Sequence record);
}