package com.github.zackwoo.scaffolding.mapper;

import com.github.zackwoo.scaffolding.entity.Signon;
import com.github.zackwoo.scaffolding.entity.SignonExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SignonMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SIGNON
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    long countByExample(SignonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SIGNON
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    int deleteByExample(SignonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SIGNON
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    int deleteByPrimaryKey(String username);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SIGNON
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    int insert(Signon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SIGNON
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    int insertSelective(Signon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SIGNON
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    List<Signon> selectByExample(SignonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SIGNON
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    Signon selectByPrimaryKey(String username);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SIGNON
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    int updateByExampleSelective(@Param("record") Signon record, @Param("example") SignonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SIGNON
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    int updateByExample(@Param("record") Signon record, @Param("example") SignonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SIGNON
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    int updateByPrimaryKeySelective(Signon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SIGNON
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    int updateByPrimaryKey(Signon record);
}