package com.github.zackwoo.scaffolding.mapper;

import com.github.zackwoo.scaffolding.entity.Supplier;
import com.github.zackwoo.scaffolding.entity.SupplierExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SupplierMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SUPPLIER
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    long countByExample(SupplierExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SUPPLIER
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    int deleteByExample(SupplierExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SUPPLIER
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    int deleteByPrimaryKey(Integer suppid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SUPPLIER
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    int insert(Supplier record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SUPPLIER
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    int insertSelective(Supplier record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SUPPLIER
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    List<Supplier> selectByExample(SupplierExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SUPPLIER
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    Supplier selectByPrimaryKey(Integer suppid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SUPPLIER
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    int updateByExampleSelective(@Param("record") Supplier record, @Param("example") SupplierExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SUPPLIER
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    int updateByExample(@Param("record") Supplier record, @Param("example") SupplierExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SUPPLIER
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    int updateByPrimaryKeySelective(Supplier record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SUPPLIER
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    int updateByPrimaryKey(Supplier record);
}