package com.github.zackwoo.scaffolding.entity;

public class Account {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACCOUNT.USERID
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    private String userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACCOUNT.EMAIL
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACCOUNT.FIRSTNAME
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    private String firstname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACCOUNT.LASTNAME
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    private String lastname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACCOUNT.STATUS
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACCOUNT.ADDR1
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    private String addr1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACCOUNT.ADDR2
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    private String addr2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACCOUNT.CITY
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    private String city;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACCOUNT.STATE
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    private String state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACCOUNT.ZIP
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    private String zip;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACCOUNT.COUNTRY
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    private String country;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACCOUNT.PHONE
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    private String phone;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACCOUNT.USERID
     *
     * @return the value of ACCOUNT.USERID
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACCOUNT.USERID
     *
     * @param userid the value for ACCOUNT.USERID
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    public void setUserid(String userid) {
        this.userid = userid == null ? null : userid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACCOUNT.EMAIL
     *
     * @return the value of ACCOUNT.EMAIL
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACCOUNT.EMAIL
     *
     * @param email the value for ACCOUNT.EMAIL
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACCOUNT.FIRSTNAME
     *
     * @return the value of ACCOUNT.FIRSTNAME
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    public String getFirstname() {
        return firstname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACCOUNT.FIRSTNAME
     *
     * @param firstname the value for ACCOUNT.FIRSTNAME
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    public void setFirstname(String firstname) {
        this.firstname = firstname == null ? null : firstname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACCOUNT.LASTNAME
     *
     * @return the value of ACCOUNT.LASTNAME
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    public String getLastname() {
        return lastname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACCOUNT.LASTNAME
     *
     * @param lastname the value for ACCOUNT.LASTNAME
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    public void setLastname(String lastname) {
        this.lastname = lastname == null ? null : lastname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACCOUNT.STATUS
     *
     * @return the value of ACCOUNT.STATUS
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACCOUNT.STATUS
     *
     * @param status the value for ACCOUNT.STATUS
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACCOUNT.ADDR1
     *
     * @return the value of ACCOUNT.ADDR1
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    public String getAddr1() {
        return addr1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACCOUNT.ADDR1
     *
     * @param addr1 the value for ACCOUNT.ADDR1
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    public void setAddr1(String addr1) {
        this.addr1 = addr1 == null ? null : addr1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACCOUNT.ADDR2
     *
     * @return the value of ACCOUNT.ADDR2
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    public String getAddr2() {
        return addr2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACCOUNT.ADDR2
     *
     * @param addr2 the value for ACCOUNT.ADDR2
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    public void setAddr2(String addr2) {
        this.addr2 = addr2 == null ? null : addr2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACCOUNT.CITY
     *
     * @return the value of ACCOUNT.CITY
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACCOUNT.CITY
     *
     * @param city the value for ACCOUNT.CITY
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACCOUNT.STATE
     *
     * @return the value of ACCOUNT.STATE
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACCOUNT.STATE
     *
     * @param state the value for ACCOUNT.STATE
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACCOUNT.ZIP
     *
     * @return the value of ACCOUNT.ZIP
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    public String getZip() {
        return zip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACCOUNT.ZIP
     *
     * @param zip the value for ACCOUNT.ZIP
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    public void setZip(String zip) {
        this.zip = zip == null ? null : zip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACCOUNT.COUNTRY
     *
     * @return the value of ACCOUNT.COUNTRY
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    public String getCountry() {
        return country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACCOUNT.COUNTRY
     *
     * @param country the value for ACCOUNT.COUNTRY
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    public void setCountry(String country) {
        this.country = country == null ? null : country.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACCOUNT.PHONE
     *
     * @return the value of ACCOUNT.PHONE
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACCOUNT.PHONE
     *
     * @param phone the value for ACCOUNT.PHONE
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }
}