package com.github.zackwoo.scaffolding.entity;

public class Category {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CATEGORY.CATID
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    private String catid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CATEGORY.NAME
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CATEGORY.DESCN
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    private String descn;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CATEGORY.CATID
     *
     * @return the value of CATEGORY.CATID
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    public String getCatid() {
        return catid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CATEGORY.CATID
     *
     * @param catid the value for CATEGORY.CATID
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    public void setCatid(String catid) {
        this.catid = catid == null ? null : catid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CATEGORY.NAME
     *
     * @return the value of CATEGORY.NAME
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CATEGORY.NAME
     *
     * @param name the value for CATEGORY.NAME
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CATEGORY.DESCN
     *
     * @return the value of CATEGORY.DESCN
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    public String getDescn() {
        return descn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CATEGORY.DESCN
     *
     * @param descn the value for CATEGORY.DESCN
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    public void setDescn(String descn) {
        this.descn = descn == null ? null : descn.trim();
    }
}