package com.github.zackwoo.scaffolding.entity;

public class CountrylanguageKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COUNTRYLANGUAGE.COUNTRYCODE
     *
     * @mbg.generated Fri Apr 14 17:57:37 CST 2017
     */
    private String countrycode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COUNTRYLANGUAGE.LANGUAGE
     *
     * @mbg.generated Fri Apr 14 17:57:37 CST 2017
     */
    private String language;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COUNTRYLANGUAGE.COUNTRYCODE
     *
     * @return the value of COUNTRYLANGUAGE.COUNTRYCODE
     *
     * @mbg.generated Fri Apr 14 17:57:37 CST 2017
     */
    public String getCountrycode() {
        return countrycode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COUNTRYLANGUAGE.COUNTRYCODE
     *
     * @param countrycode the value for COUNTRYLANGUAGE.COUNTRYCODE
     *
     * @mbg.generated Fri Apr 14 17:57:37 CST 2017
     */
    public void setCountrycode(String countrycode) {
        this.countrycode = countrycode == null ? null : countrycode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COUNTRYLANGUAGE.LANGUAGE
     *
     * @return the value of COUNTRYLANGUAGE.LANGUAGE
     *
     * @mbg.generated Fri Apr 14 17:57:37 CST 2017
     */
    public String getLanguage() {
        return language;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COUNTRYLANGUAGE.LANGUAGE
     *
     * @param language the value for COUNTRYLANGUAGE.LANGUAGE
     *
     * @mbg.generated Fri Apr 14 17:57:37 CST 2017
     */
    public void setLanguage(String language) {
        this.language = language == null ? null : language.trim();
    }
}