package com.github.zackwoo.scaffolding.entity;

import java.util.ArrayList;
import java.util.List;

public class CountrylanguageExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table COUNTRYLANGUAGE
     *
     * @mbg.generated Wed Apr 12 11:10:29 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table COUNTRYLANGUAGE
     *
     * @mbg.generated Wed Apr 12 11:10:29 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table COUNTRYLANGUAGE
     *
     * @mbg.generated Wed Apr 12 11:10:29 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COUNTRYLANGUAGE
     *
     * @mbg.generated Wed Apr 12 11:10:29 CST 2017
     */
    public CountrylanguageExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COUNTRYLANGUAGE
     *
     * @mbg.generated Wed Apr 12 11:10:29 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COUNTRYLANGUAGE
     *
     * @mbg.generated Wed Apr 12 11:10:29 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COUNTRYLANGUAGE
     *
     * @mbg.generated Wed Apr 12 11:10:29 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COUNTRYLANGUAGE
     *
     * @mbg.generated Wed Apr 12 11:10:29 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COUNTRYLANGUAGE
     *
     * @mbg.generated Wed Apr 12 11:10:29 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COUNTRYLANGUAGE
     *
     * @mbg.generated Wed Apr 12 11:10:29 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COUNTRYLANGUAGE
     *
     * @mbg.generated Wed Apr 12 11:10:29 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COUNTRYLANGUAGE
     *
     * @mbg.generated Wed Apr 12 11:10:29 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COUNTRYLANGUAGE
     *
     * @mbg.generated Wed Apr 12 11:10:29 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COUNTRYLANGUAGE
     *
     * @mbg.generated Wed Apr 12 11:10:29 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table COUNTRYLANGUAGE
     *
     * @mbg.generated Wed Apr 12 11:10:29 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andCountrycodeIsNull() {
            addCriterion("COUNTRYCODE is null");
            return (Criteria) this;
        }

        public Criteria andCountrycodeIsNotNull() {
            addCriterion("COUNTRYCODE is not null");
            return (Criteria) this;
        }

        public Criteria andCountrycodeEqualTo(String value) {
            addCriterion("COUNTRYCODE =", value, "countrycode");
            return (Criteria) this;
        }

        public Criteria andCountrycodeNotEqualTo(String value) {
            addCriterion("COUNTRYCODE <>", value, "countrycode");
            return (Criteria) this;
        }

        public Criteria andCountrycodeGreaterThan(String value) {
            addCriterion("COUNTRYCODE >", value, "countrycode");
            return (Criteria) this;
        }

        public Criteria andCountrycodeGreaterThanOrEqualTo(String value) {
            addCriterion("COUNTRYCODE >=", value, "countrycode");
            return (Criteria) this;
        }

        public Criteria andCountrycodeLessThan(String value) {
            addCriterion("COUNTRYCODE <", value, "countrycode");
            return (Criteria) this;
        }

        public Criteria andCountrycodeLessThanOrEqualTo(String value) {
            addCriterion("COUNTRYCODE <=", value, "countrycode");
            return (Criteria) this;
        }

        public Criteria andCountrycodeLike(String value) {
            addCriterion("COUNTRYCODE like", value, "countrycode");
            return (Criteria) this;
        }

        public Criteria andCountrycodeNotLike(String value) {
            addCriterion("COUNTRYCODE not like", value, "countrycode");
            return (Criteria) this;
        }

        public Criteria andCountrycodeIn(List<String> values) {
            addCriterion("COUNTRYCODE in", values, "countrycode");
            return (Criteria) this;
        }

        public Criteria andCountrycodeNotIn(List<String> values) {
            addCriterion("COUNTRYCODE not in", values, "countrycode");
            return (Criteria) this;
        }

        public Criteria andCountrycodeBetween(String value1, String value2) {
            addCriterion("COUNTRYCODE between", value1, value2, "countrycode");
            return (Criteria) this;
        }

        public Criteria andCountrycodeNotBetween(String value1, String value2) {
            addCriterion("COUNTRYCODE not between", value1, value2, "countrycode");
            return (Criteria) this;
        }

        public Criteria andLanguageIsNull() {
            addCriterion("LANGUAGE is null");
            return (Criteria) this;
        }

        public Criteria andLanguageIsNotNull() {
            addCriterion("LANGUAGE is not null");
            return (Criteria) this;
        }

        public Criteria andLanguageEqualTo(String value) {
            addCriterion("LANGUAGE =", value, "language");
            return (Criteria) this;
        }

        public Criteria andLanguageNotEqualTo(String value) {
            addCriterion("LANGUAGE <>", value, "language");
            return (Criteria) this;
        }

        public Criteria andLanguageGreaterThan(String value) {
            addCriterion("LANGUAGE >", value, "language");
            return (Criteria) this;
        }

        public Criteria andLanguageGreaterThanOrEqualTo(String value) {
            addCriterion("LANGUAGE >=", value, "language");
            return (Criteria) this;
        }

        public Criteria andLanguageLessThan(String value) {
            addCriterion("LANGUAGE <", value, "language");
            return (Criteria) this;
        }

        public Criteria andLanguageLessThanOrEqualTo(String value) {
            addCriterion("LANGUAGE <=", value, "language");
            return (Criteria) this;
        }

        public Criteria andLanguageLike(String value) {
            addCriterion("LANGUAGE like", value, "language");
            return (Criteria) this;
        }

        public Criteria andLanguageNotLike(String value) {
            addCriterion("LANGUAGE not like", value, "language");
            return (Criteria) this;
        }

        public Criteria andLanguageIn(List<String> values) {
            addCriterion("LANGUAGE in", values, "language");
            return (Criteria) this;
        }

        public Criteria andLanguageNotIn(List<String> values) {
            addCriterion("LANGUAGE not in", values, "language");
            return (Criteria) this;
        }

        public Criteria andLanguageBetween(String value1, String value2) {
            addCriterion("LANGUAGE between", value1, value2, "language");
            return (Criteria) this;
        }

        public Criteria andLanguageNotBetween(String value1, String value2) {
            addCriterion("LANGUAGE not between", value1, value2, "language");
            return (Criteria) this;
        }

        public Criteria andIsofficialIsNull() {
            addCriterion("ISOFFICIAL is null");
            return (Criteria) this;
        }

        public Criteria andIsofficialIsNotNull() {
            addCriterion("ISOFFICIAL is not null");
            return (Criteria) this;
        }

        public Criteria andIsofficialEqualTo(String value) {
            addCriterion("ISOFFICIAL =", value, "isofficial");
            return (Criteria) this;
        }

        public Criteria andIsofficialNotEqualTo(String value) {
            addCriterion("ISOFFICIAL <>", value, "isofficial");
            return (Criteria) this;
        }

        public Criteria andIsofficialGreaterThan(String value) {
            addCriterion("ISOFFICIAL >", value, "isofficial");
            return (Criteria) this;
        }

        public Criteria andIsofficialGreaterThanOrEqualTo(String value) {
            addCriterion("ISOFFICIAL >=", value, "isofficial");
            return (Criteria) this;
        }

        public Criteria andIsofficialLessThan(String value) {
            addCriterion("ISOFFICIAL <", value, "isofficial");
            return (Criteria) this;
        }

        public Criteria andIsofficialLessThanOrEqualTo(String value) {
            addCriterion("ISOFFICIAL <=", value, "isofficial");
            return (Criteria) this;
        }

        public Criteria andIsofficialLike(String value) {
            addCriterion("ISOFFICIAL like", value, "isofficial");
            return (Criteria) this;
        }

        public Criteria andIsofficialNotLike(String value) {
            addCriterion("ISOFFICIAL not like", value, "isofficial");
            return (Criteria) this;
        }

        public Criteria andIsofficialIn(List<String> values) {
            addCriterion("ISOFFICIAL in", values, "isofficial");
            return (Criteria) this;
        }

        public Criteria andIsofficialNotIn(List<String> values) {
            addCriterion("ISOFFICIAL not in", values, "isofficial");
            return (Criteria) this;
        }

        public Criteria andIsofficialBetween(String value1, String value2) {
            addCriterion("ISOFFICIAL between", value1, value2, "isofficial");
            return (Criteria) this;
        }

        public Criteria andIsofficialNotBetween(String value1, String value2) {
            addCriterion("ISOFFICIAL not between", value1, value2, "isofficial");
            return (Criteria) this;
        }

        public Criteria andPercentageIsNull() {
            addCriterion("PERCENTAGE is null");
            return (Criteria) this;
        }

        public Criteria andPercentageIsNotNull() {
            addCriterion("PERCENTAGE is not null");
            return (Criteria) this;
        }

        public Criteria andPercentageEqualTo(Double value) {
            addCriterion("PERCENTAGE =", value, "percentage");
            return (Criteria) this;
        }

        public Criteria andPercentageNotEqualTo(Double value) {
            addCriterion("PERCENTAGE <>", value, "percentage");
            return (Criteria) this;
        }

        public Criteria andPercentageGreaterThan(Double value) {
            addCriterion("PERCENTAGE >", value, "percentage");
            return (Criteria) this;
        }

        public Criteria andPercentageGreaterThanOrEqualTo(Double value) {
            addCriterion("PERCENTAGE >=", value, "percentage");
            return (Criteria) this;
        }

        public Criteria andPercentageLessThan(Double value) {
            addCriterion("PERCENTAGE <", value, "percentage");
            return (Criteria) this;
        }

        public Criteria andPercentageLessThanOrEqualTo(Double value) {
            addCriterion("PERCENTAGE <=", value, "percentage");
            return (Criteria) this;
        }

        public Criteria andPercentageIn(List<Double> values) {
            addCriterion("PERCENTAGE in", values, "percentage");
            return (Criteria) this;
        }

        public Criteria andPercentageNotIn(List<Double> values) {
            addCriterion("PERCENTAGE not in", values, "percentage");
            return (Criteria) this;
        }

        public Criteria andPercentageBetween(Double value1, Double value2) {
            addCriterion("PERCENTAGE between", value1, value2, "percentage");
            return (Criteria) this;
        }

        public Criteria andPercentageNotBetween(Double value1, Double value2) {
            addCriterion("PERCENTAGE not between", value1, value2, "percentage");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table COUNTRYLANGUAGE
     *
     * @mbg.generated do_not_delete_during_merge Wed Apr 12 11:10:29 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table COUNTRYLANGUAGE
     *
     * @mbg.generated Wed Apr 12 11:10:29 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}