package com.github.zackwoo.scaffolding.entity;

public class Country {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COUNTRY.CODE
     *
     * @mbg.generated Fri Apr 14 17:57:37 CST 2017
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COUNTRY.NAME
     *
     * @mbg.generated Fri Apr 14 17:57:37 CST 2017
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COUNTRY.CONTINENT
     *
     * @mbg.generated Fri Apr 14 17:57:37 CST 2017
     */
    private String continent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COUNTRY.REGION
     *
     * @mbg.generated Fri Apr 14 17:57:37 CST 2017
     */
    private String region;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COUNTRY.SURFACEAREA
     *
     * @mbg.generated Fri Apr 14 17:57:37 CST 2017
     */
    private Double surfacearea;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COUNTRY.INDEPYEAR
     *
     * @mbg.generated Fri Apr 14 17:57:37 CST 2017
     */
    private Short indepyear;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COUNTRY.POPULATION
     *
     * @mbg.generated Fri Apr 14 17:57:37 CST 2017
     */
    private Integer population;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COUNTRY.LIFEEXPECTANCY
     *
     * @mbg.generated Fri Apr 14 17:57:37 CST 2017
     */
    private Double lifeexpectancy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COUNTRY.GNP
     *
     * @mbg.generated Fri Apr 14 17:57:37 CST 2017
     */
    private Double gnp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COUNTRY.GNPOLD
     *
     * @mbg.generated Fri Apr 14 17:57:37 CST 2017
     */
    private Double gnpold;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COUNTRY.LOCALNAME
     *
     * @mbg.generated Fri Apr 14 17:57:37 CST 2017
     */
    private String localname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COUNTRY.GOVERNMENTFORM
     *
     * @mbg.generated Fri Apr 14 17:57:37 CST 2017
     */
    private String governmentform;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COUNTRY.HEADOFSTATE
     *
     * @mbg.generated Fri Apr 14 17:57:37 CST 2017
     */
    private String headofstate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COUNTRY.CAPITAL
     *
     * @mbg.generated Fri Apr 14 17:57:37 CST 2017
     */
    private Integer capital;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COUNTRY.CODE2
     *
     * @mbg.generated Fri Apr 14 17:57:37 CST 2017
     */
    private String code2;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COUNTRY.CODE
     *
     * @return the value of COUNTRY.CODE
     *
     * @mbg.generated Fri Apr 14 17:57:37 CST 2017
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COUNTRY.CODE
     *
     * @param code the value for COUNTRY.CODE
     *
     * @mbg.generated Fri Apr 14 17:57:37 CST 2017
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COUNTRY.NAME
     *
     * @return the value of COUNTRY.NAME
     *
     * @mbg.generated Fri Apr 14 17:57:37 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COUNTRY.NAME
     *
     * @param name the value for COUNTRY.NAME
     *
     * @mbg.generated Fri Apr 14 17:57:37 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COUNTRY.CONTINENT
     *
     * @return the value of COUNTRY.CONTINENT
     *
     * @mbg.generated Fri Apr 14 17:57:37 CST 2017
     */
    public String getContinent() {
        return continent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COUNTRY.CONTINENT
     *
     * @param continent the value for COUNTRY.CONTINENT
     *
     * @mbg.generated Fri Apr 14 17:57:37 CST 2017
     */
    public void setContinent(String continent) {
        this.continent = continent == null ? null : continent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COUNTRY.REGION
     *
     * @return the value of COUNTRY.REGION
     *
     * @mbg.generated Fri Apr 14 17:57:37 CST 2017
     */
    public String getRegion() {
        return region;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COUNTRY.REGION
     *
     * @param region the value for COUNTRY.REGION
     *
     * @mbg.generated Fri Apr 14 17:57:37 CST 2017
     */
    public void setRegion(String region) {
        this.region = region == null ? null : region.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COUNTRY.SURFACEAREA
     *
     * @return the value of COUNTRY.SURFACEAREA
     *
     * @mbg.generated Fri Apr 14 17:57:37 CST 2017
     */
    public Double getSurfacearea() {
        return surfacearea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COUNTRY.SURFACEAREA
     *
     * @param surfacearea the value for COUNTRY.SURFACEAREA
     *
     * @mbg.generated Fri Apr 14 17:57:37 CST 2017
     */
    public void setSurfacearea(Double surfacearea) {
        this.surfacearea = surfacearea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COUNTRY.INDEPYEAR
     *
     * @return the value of COUNTRY.INDEPYEAR
     *
     * @mbg.generated Fri Apr 14 17:57:37 CST 2017
     */
    public Short getIndepyear() {
        return indepyear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COUNTRY.INDEPYEAR
     *
     * @param indepyear the value for COUNTRY.INDEPYEAR
     *
     * @mbg.generated Fri Apr 14 17:57:37 CST 2017
     */
    public void setIndepyear(Short indepyear) {
        this.indepyear = indepyear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COUNTRY.POPULATION
     *
     * @return the value of COUNTRY.POPULATION
     *
     * @mbg.generated Fri Apr 14 17:57:37 CST 2017
     */
    public Integer getPopulation() {
        return population;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COUNTRY.POPULATION
     *
     * @param population the value for COUNTRY.POPULATION
     *
     * @mbg.generated Fri Apr 14 17:57:37 CST 2017
     */
    public void setPopulation(Integer population) {
        this.population = population;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COUNTRY.LIFEEXPECTANCY
     *
     * @return the value of COUNTRY.LIFEEXPECTANCY
     *
     * @mbg.generated Fri Apr 14 17:57:37 CST 2017
     */
    public Double getLifeexpectancy() {
        return lifeexpectancy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COUNTRY.LIFEEXPECTANCY
     *
     * @param lifeexpectancy the value for COUNTRY.LIFEEXPECTANCY
     *
     * @mbg.generated Fri Apr 14 17:57:37 CST 2017
     */
    public void setLifeexpectancy(Double lifeexpectancy) {
        this.lifeexpectancy = lifeexpectancy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COUNTRY.GNP
     *
     * @return the value of COUNTRY.GNP
     *
     * @mbg.generated Fri Apr 14 17:57:37 CST 2017
     */
    public Double getGnp() {
        return gnp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COUNTRY.GNP
     *
     * @param gnp the value for COUNTRY.GNP
     *
     * @mbg.generated Fri Apr 14 17:57:37 CST 2017
     */
    public void setGnp(Double gnp) {
        this.gnp = gnp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COUNTRY.GNPOLD
     *
     * @return the value of COUNTRY.GNPOLD
     *
     * @mbg.generated Fri Apr 14 17:57:37 CST 2017
     */
    public Double getGnpold() {
        return gnpold;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COUNTRY.GNPOLD
     *
     * @param gnpold the value for COUNTRY.GNPOLD
     *
     * @mbg.generated Fri Apr 14 17:57:37 CST 2017
     */
    public void setGnpold(Double gnpold) {
        this.gnpold = gnpold;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COUNTRY.LOCALNAME
     *
     * @return the value of COUNTRY.LOCALNAME
     *
     * @mbg.generated Fri Apr 14 17:57:37 CST 2017
     */
    public String getLocalname() {
        return localname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COUNTRY.LOCALNAME
     *
     * @param localname the value for COUNTRY.LOCALNAME
     *
     * @mbg.generated Fri Apr 14 17:57:37 CST 2017
     */
    public void setLocalname(String localname) {
        this.localname = localname == null ? null : localname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COUNTRY.GOVERNMENTFORM
     *
     * @return the value of COUNTRY.GOVERNMENTFORM
     *
     * @mbg.generated Fri Apr 14 17:57:37 CST 2017
     */
    public String getGovernmentform() {
        return governmentform;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COUNTRY.GOVERNMENTFORM
     *
     * @param governmentform the value for COUNTRY.GOVERNMENTFORM
     *
     * @mbg.generated Fri Apr 14 17:57:37 CST 2017
     */
    public void setGovernmentform(String governmentform) {
        this.governmentform = governmentform == null ? null : governmentform.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COUNTRY.HEADOFSTATE
     *
     * @return the value of COUNTRY.HEADOFSTATE
     *
     * @mbg.generated Fri Apr 14 17:57:37 CST 2017
     */
    public String getHeadofstate() {
        return headofstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COUNTRY.HEADOFSTATE
     *
     * @param headofstate the value for COUNTRY.HEADOFSTATE
     *
     * @mbg.generated Fri Apr 14 17:57:37 CST 2017
     */
    public void setHeadofstate(String headofstate) {
        this.headofstate = headofstate == null ? null : headofstate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COUNTRY.CAPITAL
     *
     * @return the value of COUNTRY.CAPITAL
     *
     * @mbg.generated Fri Apr 14 17:57:37 CST 2017
     */
    public Integer getCapital() {
        return capital;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COUNTRY.CAPITAL
     *
     * @param capital the value for COUNTRY.CAPITAL
     *
     * @mbg.generated Fri Apr 14 17:57:37 CST 2017
     */
    public void setCapital(Integer capital) {
        this.capital = capital;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COUNTRY.CODE2
     *
     * @return the value of COUNTRY.CODE2
     *
     * @mbg.generated Fri Apr 14 17:57:37 CST 2017
     */
    public String getCode2() {
        return code2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COUNTRY.CODE2
     *
     * @param code2 the value for COUNTRY.CODE2
     *
     * @mbg.generated Fri Apr 14 17:57:37 CST 2017
     */
    public void setCode2(String code2) {
        this.code2 = code2 == null ? null : code2.trim();
    }
}