package com.github.zackwoo.scaffolding.entity;

public class Inventory {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INVENTORY.ITEMID
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    private String itemid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INVENTORY.QTY
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    private Integer qty;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INVENTORY.ITEMID
     *
     * @return the value of INVENTORY.ITEMID
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    public String getItemid() {
        return itemid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INVENTORY.ITEMID
     *
     * @param itemid the value for INVENTORY.ITEMID
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    public void setItemid(String itemid) {
        this.itemid = itemid == null ? null : itemid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INVENTORY.QTY
     *
     * @return the value of INVENTORY.QTY
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    public Integer getQty() {
        return qty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INVENTORY.QTY
     *
     * @param qty the value for INVENTORY.QTY
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    public void setQty(Integer qty) {
        this.qty = qty;
    }
}