package com.github.zackwoo.scaffolding.entity;

public class LineitemKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LINEITEM.ORDERID
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    private Integer orderid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LINEITEM.LINENUM
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    private Integer linenum;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LINEITEM.ORDERID
     *
     * @return the value of LINEITEM.ORDERID
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    public Integer getOrderid() {
        return orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LINEITEM.ORDERID
     *
     * @param orderid the value for LINEITEM.ORDERID
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    public void setOrderid(Integer orderid) {
        this.orderid = orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LINEITEM.LINENUM
     *
     * @return the value of LINEITEM.LINENUM
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    public Integer getLinenum() {
        return linenum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LINEITEM.LINENUM
     *
     * @param linenum the value for LINEITEM.LINENUM
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    public void setLinenum(Integer linenum) {
        this.linenum = linenum;
    }
}