package com.github.zackwoo.scaffolding.entity;

import java.math.BigDecimal;
import java.util.Date;

public class Orders {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDERS.ORDERID
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    private Integer orderid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDERS.USERID
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    private String userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDERS.ORDERDATE
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    private Date orderdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDERS.SHIPADDR1
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    private String shipaddr1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDERS.SHIPADDR2
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    private String shipaddr2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDERS.SHIPCITY
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    private String shipcity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDERS.SHIPSTATE
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    private String shipstate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDERS.SHIPZIP
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    private String shipzip;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDERS.SHIPCOUNTRY
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    private String shipcountry;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDERS.BILLADDR1
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    private String billaddr1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDERS.BILLADDR2
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    private String billaddr2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDERS.BILLCITY
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    private String billcity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDERS.BILLSTATE
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    private String billstate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDERS.BILLZIP
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    private String billzip;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDERS.BILLCOUNTRY
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    private String billcountry;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDERS.COURIER
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    private String courier;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDERS.TOTALPRICE
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    private BigDecimal totalprice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDERS.BILLTOFIRSTNAME
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    private String billtofirstname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDERS.BILLTOLASTNAME
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    private String billtolastname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDERS.SHIPTOFIRSTNAME
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    private String shiptofirstname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDERS.SHIPTOLASTNAME
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    private String shiptolastname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDERS.CREDITCARD
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    private String creditcard;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDERS.EXPRDATE
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    private String exprdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDERS.CARDTYPE
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    private String cardtype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDERS.LOCALE
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    private String locale;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDERS.ORDERID
     *
     * @return the value of ORDERS.ORDERID
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    public Integer getOrderid() {
        return orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDERS.ORDERID
     *
     * @param orderid the value for ORDERS.ORDERID
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    public void setOrderid(Integer orderid) {
        this.orderid = orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDERS.USERID
     *
     * @return the value of ORDERS.USERID
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDERS.USERID
     *
     * @param userid the value for ORDERS.USERID
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    public void setUserid(String userid) {
        this.userid = userid == null ? null : userid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDERS.ORDERDATE
     *
     * @return the value of ORDERS.ORDERDATE
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    public Date getOrderdate() {
        return orderdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDERS.ORDERDATE
     *
     * @param orderdate the value for ORDERS.ORDERDATE
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    public void setOrderdate(Date orderdate) {
        this.orderdate = orderdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDERS.SHIPADDR1
     *
     * @return the value of ORDERS.SHIPADDR1
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    public String getShipaddr1() {
        return shipaddr1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDERS.SHIPADDR1
     *
     * @param shipaddr1 the value for ORDERS.SHIPADDR1
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    public void setShipaddr1(String shipaddr1) {
        this.shipaddr1 = shipaddr1 == null ? null : shipaddr1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDERS.SHIPADDR2
     *
     * @return the value of ORDERS.SHIPADDR2
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    public String getShipaddr2() {
        return shipaddr2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDERS.SHIPADDR2
     *
     * @param shipaddr2 the value for ORDERS.SHIPADDR2
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    public void setShipaddr2(String shipaddr2) {
        this.shipaddr2 = shipaddr2 == null ? null : shipaddr2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDERS.SHIPCITY
     *
     * @return the value of ORDERS.SHIPCITY
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    public String getShipcity() {
        return shipcity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDERS.SHIPCITY
     *
     * @param shipcity the value for ORDERS.SHIPCITY
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    public void setShipcity(String shipcity) {
        this.shipcity = shipcity == null ? null : shipcity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDERS.SHIPSTATE
     *
     * @return the value of ORDERS.SHIPSTATE
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    public String getShipstate() {
        return shipstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDERS.SHIPSTATE
     *
     * @param shipstate the value for ORDERS.SHIPSTATE
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    public void setShipstate(String shipstate) {
        this.shipstate = shipstate == null ? null : shipstate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDERS.SHIPZIP
     *
     * @return the value of ORDERS.SHIPZIP
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    public String getShipzip() {
        return shipzip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDERS.SHIPZIP
     *
     * @param shipzip the value for ORDERS.SHIPZIP
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    public void setShipzip(String shipzip) {
        this.shipzip = shipzip == null ? null : shipzip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDERS.SHIPCOUNTRY
     *
     * @return the value of ORDERS.SHIPCOUNTRY
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    public String getShipcountry() {
        return shipcountry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDERS.SHIPCOUNTRY
     *
     * @param shipcountry the value for ORDERS.SHIPCOUNTRY
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    public void setShipcountry(String shipcountry) {
        this.shipcountry = shipcountry == null ? null : shipcountry.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDERS.BILLADDR1
     *
     * @return the value of ORDERS.BILLADDR1
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    public String getBilladdr1() {
        return billaddr1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDERS.BILLADDR1
     *
     * @param billaddr1 the value for ORDERS.BILLADDR1
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    public void setBilladdr1(String billaddr1) {
        this.billaddr1 = billaddr1 == null ? null : billaddr1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDERS.BILLADDR2
     *
     * @return the value of ORDERS.BILLADDR2
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    public String getBilladdr2() {
        return billaddr2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDERS.BILLADDR2
     *
     * @param billaddr2 the value for ORDERS.BILLADDR2
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    public void setBilladdr2(String billaddr2) {
        this.billaddr2 = billaddr2 == null ? null : billaddr2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDERS.BILLCITY
     *
     * @return the value of ORDERS.BILLCITY
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    public String getBillcity() {
        return billcity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDERS.BILLCITY
     *
     * @param billcity the value for ORDERS.BILLCITY
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    public void setBillcity(String billcity) {
        this.billcity = billcity == null ? null : billcity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDERS.BILLSTATE
     *
     * @return the value of ORDERS.BILLSTATE
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    public String getBillstate() {
        return billstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDERS.BILLSTATE
     *
     * @param billstate the value for ORDERS.BILLSTATE
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    public void setBillstate(String billstate) {
        this.billstate = billstate == null ? null : billstate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDERS.BILLZIP
     *
     * @return the value of ORDERS.BILLZIP
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    public String getBillzip() {
        return billzip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDERS.BILLZIP
     *
     * @param billzip the value for ORDERS.BILLZIP
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    public void setBillzip(String billzip) {
        this.billzip = billzip == null ? null : billzip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDERS.BILLCOUNTRY
     *
     * @return the value of ORDERS.BILLCOUNTRY
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    public String getBillcountry() {
        return billcountry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDERS.BILLCOUNTRY
     *
     * @param billcountry the value for ORDERS.BILLCOUNTRY
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    public void setBillcountry(String billcountry) {
        this.billcountry = billcountry == null ? null : billcountry.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDERS.COURIER
     *
     * @return the value of ORDERS.COURIER
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    public String getCourier() {
        return courier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDERS.COURIER
     *
     * @param courier the value for ORDERS.COURIER
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    public void setCourier(String courier) {
        this.courier = courier == null ? null : courier.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDERS.TOTALPRICE
     *
     * @return the value of ORDERS.TOTALPRICE
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    public BigDecimal getTotalprice() {
        return totalprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDERS.TOTALPRICE
     *
     * @param totalprice the value for ORDERS.TOTALPRICE
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    public void setTotalprice(BigDecimal totalprice) {
        this.totalprice = totalprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDERS.BILLTOFIRSTNAME
     *
     * @return the value of ORDERS.BILLTOFIRSTNAME
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    public String getBilltofirstname() {
        return billtofirstname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDERS.BILLTOFIRSTNAME
     *
     * @param billtofirstname the value for ORDERS.BILLTOFIRSTNAME
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    public void setBilltofirstname(String billtofirstname) {
        this.billtofirstname = billtofirstname == null ? null : billtofirstname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDERS.BILLTOLASTNAME
     *
     * @return the value of ORDERS.BILLTOLASTNAME
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    public String getBilltolastname() {
        return billtolastname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDERS.BILLTOLASTNAME
     *
     * @param billtolastname the value for ORDERS.BILLTOLASTNAME
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    public void setBilltolastname(String billtolastname) {
        this.billtolastname = billtolastname == null ? null : billtolastname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDERS.SHIPTOFIRSTNAME
     *
     * @return the value of ORDERS.SHIPTOFIRSTNAME
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    public String getShiptofirstname() {
        return shiptofirstname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDERS.SHIPTOFIRSTNAME
     *
     * @param shiptofirstname the value for ORDERS.SHIPTOFIRSTNAME
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    public void setShiptofirstname(String shiptofirstname) {
        this.shiptofirstname = shiptofirstname == null ? null : shiptofirstname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDERS.SHIPTOLASTNAME
     *
     * @return the value of ORDERS.SHIPTOLASTNAME
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    public String getShiptolastname() {
        return shiptolastname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDERS.SHIPTOLASTNAME
     *
     * @param shiptolastname the value for ORDERS.SHIPTOLASTNAME
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    public void setShiptolastname(String shiptolastname) {
        this.shiptolastname = shiptolastname == null ? null : shiptolastname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDERS.CREDITCARD
     *
     * @return the value of ORDERS.CREDITCARD
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    public String getCreditcard() {
        return creditcard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDERS.CREDITCARD
     *
     * @param creditcard the value for ORDERS.CREDITCARD
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    public void setCreditcard(String creditcard) {
        this.creditcard = creditcard == null ? null : creditcard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDERS.EXPRDATE
     *
     * @return the value of ORDERS.EXPRDATE
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    public String getExprdate() {
        return exprdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDERS.EXPRDATE
     *
     * @param exprdate the value for ORDERS.EXPRDATE
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    public void setExprdate(String exprdate) {
        this.exprdate = exprdate == null ? null : exprdate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDERS.CARDTYPE
     *
     * @return the value of ORDERS.CARDTYPE
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    public String getCardtype() {
        return cardtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDERS.CARDTYPE
     *
     * @param cardtype the value for ORDERS.CARDTYPE
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    public void setCardtype(String cardtype) {
        this.cardtype = cardtype == null ? null : cardtype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDERS.LOCALE
     *
     * @return the value of ORDERS.LOCALE
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    public String getLocale() {
        return locale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDERS.LOCALE
     *
     * @param locale the value for ORDERS.LOCALE
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    public void setLocale(String locale) {
        this.locale = locale == null ? null : locale.trim();
    }
}