package com.github.zackwoo.scaffolding.entity;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class OrdersExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ORDERS
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ORDERS
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ORDERS
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORDERS
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    public OrdersExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORDERS
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORDERS
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORDERS
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORDERS
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORDERS
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORDERS
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORDERS
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORDERS
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORDERS
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORDERS
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ORDERS
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andOrderidIsNull() {
            addCriterion("ORDERID is null");
            return (Criteria) this;
        }

        public Criteria andOrderidIsNotNull() {
            addCriterion("ORDERID is not null");
            return (Criteria) this;
        }

        public Criteria andOrderidEqualTo(Integer value) {
            addCriterion("ORDERID =", value, "orderid");
            return (Criteria) this;
        }

        public Criteria andOrderidNotEqualTo(Integer value) {
            addCriterion("ORDERID <>", value, "orderid");
            return (Criteria) this;
        }

        public Criteria andOrderidGreaterThan(Integer value) {
            addCriterion("ORDERID >", value, "orderid");
            return (Criteria) this;
        }

        public Criteria andOrderidGreaterThanOrEqualTo(Integer value) {
            addCriterion("ORDERID >=", value, "orderid");
            return (Criteria) this;
        }

        public Criteria andOrderidLessThan(Integer value) {
            addCriterion("ORDERID <", value, "orderid");
            return (Criteria) this;
        }

        public Criteria andOrderidLessThanOrEqualTo(Integer value) {
            addCriterion("ORDERID <=", value, "orderid");
            return (Criteria) this;
        }

        public Criteria andOrderidIn(List<Integer> values) {
            addCriterion("ORDERID in", values, "orderid");
            return (Criteria) this;
        }

        public Criteria andOrderidNotIn(List<Integer> values) {
            addCriterion("ORDERID not in", values, "orderid");
            return (Criteria) this;
        }

        public Criteria andOrderidBetween(Integer value1, Integer value2) {
            addCriterion("ORDERID between", value1, value2, "orderid");
            return (Criteria) this;
        }

        public Criteria andOrderidNotBetween(Integer value1, Integer value2) {
            addCriterion("ORDERID not between", value1, value2, "orderid");
            return (Criteria) this;
        }

        public Criteria andUseridIsNull() {
            addCriterion("USERID is null");
            return (Criteria) this;
        }

        public Criteria andUseridIsNotNull() {
            addCriterion("USERID is not null");
            return (Criteria) this;
        }

        public Criteria andUseridEqualTo(String value) {
            addCriterion("USERID =", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridNotEqualTo(String value) {
            addCriterion("USERID <>", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridGreaterThan(String value) {
            addCriterion("USERID >", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridGreaterThanOrEqualTo(String value) {
            addCriterion("USERID >=", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridLessThan(String value) {
            addCriterion("USERID <", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridLessThanOrEqualTo(String value) {
            addCriterion("USERID <=", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridLike(String value) {
            addCriterion("USERID like", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridNotLike(String value) {
            addCriterion("USERID not like", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridIn(List<String> values) {
            addCriterion("USERID in", values, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridNotIn(List<String> values) {
            addCriterion("USERID not in", values, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridBetween(String value1, String value2) {
            addCriterion("USERID between", value1, value2, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridNotBetween(String value1, String value2) {
            addCriterion("USERID not between", value1, value2, "userid");
            return (Criteria) this;
        }

        public Criteria andOrderdateIsNull() {
            addCriterion("ORDERDATE is null");
            return (Criteria) this;
        }

        public Criteria andOrderdateIsNotNull() {
            addCriterion("ORDERDATE is not null");
            return (Criteria) this;
        }

        public Criteria andOrderdateEqualTo(Date value) {
            addCriterionForJDBCDate("ORDERDATE =", value, "orderdate");
            return (Criteria) this;
        }

        public Criteria andOrderdateNotEqualTo(Date value) {
            addCriterionForJDBCDate("ORDERDATE <>", value, "orderdate");
            return (Criteria) this;
        }

        public Criteria andOrderdateGreaterThan(Date value) {
            addCriterionForJDBCDate("ORDERDATE >", value, "orderdate");
            return (Criteria) this;
        }

        public Criteria andOrderdateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("ORDERDATE >=", value, "orderdate");
            return (Criteria) this;
        }

        public Criteria andOrderdateLessThan(Date value) {
            addCriterionForJDBCDate("ORDERDATE <", value, "orderdate");
            return (Criteria) this;
        }

        public Criteria andOrderdateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("ORDERDATE <=", value, "orderdate");
            return (Criteria) this;
        }

        public Criteria andOrderdateIn(List<Date> values) {
            addCriterionForJDBCDate("ORDERDATE in", values, "orderdate");
            return (Criteria) this;
        }

        public Criteria andOrderdateNotIn(List<Date> values) {
            addCriterionForJDBCDate("ORDERDATE not in", values, "orderdate");
            return (Criteria) this;
        }

        public Criteria andOrderdateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("ORDERDATE between", value1, value2, "orderdate");
            return (Criteria) this;
        }

        public Criteria andOrderdateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("ORDERDATE not between", value1, value2, "orderdate");
            return (Criteria) this;
        }

        public Criteria andShipaddr1IsNull() {
            addCriterion("SHIPADDR1 is null");
            return (Criteria) this;
        }

        public Criteria andShipaddr1IsNotNull() {
            addCriterion("SHIPADDR1 is not null");
            return (Criteria) this;
        }

        public Criteria andShipaddr1EqualTo(String value) {
            addCriterion("SHIPADDR1 =", value, "shipaddr1");
            return (Criteria) this;
        }

        public Criteria andShipaddr1NotEqualTo(String value) {
            addCriterion("SHIPADDR1 <>", value, "shipaddr1");
            return (Criteria) this;
        }

        public Criteria andShipaddr1GreaterThan(String value) {
            addCriterion("SHIPADDR1 >", value, "shipaddr1");
            return (Criteria) this;
        }

        public Criteria andShipaddr1GreaterThanOrEqualTo(String value) {
            addCriterion("SHIPADDR1 >=", value, "shipaddr1");
            return (Criteria) this;
        }

        public Criteria andShipaddr1LessThan(String value) {
            addCriterion("SHIPADDR1 <", value, "shipaddr1");
            return (Criteria) this;
        }

        public Criteria andShipaddr1LessThanOrEqualTo(String value) {
            addCriterion("SHIPADDR1 <=", value, "shipaddr1");
            return (Criteria) this;
        }

        public Criteria andShipaddr1Like(String value) {
            addCriterion("SHIPADDR1 like", value, "shipaddr1");
            return (Criteria) this;
        }

        public Criteria andShipaddr1NotLike(String value) {
            addCriterion("SHIPADDR1 not like", value, "shipaddr1");
            return (Criteria) this;
        }

        public Criteria andShipaddr1In(List<String> values) {
            addCriterion("SHIPADDR1 in", values, "shipaddr1");
            return (Criteria) this;
        }

        public Criteria andShipaddr1NotIn(List<String> values) {
            addCriterion("SHIPADDR1 not in", values, "shipaddr1");
            return (Criteria) this;
        }

        public Criteria andShipaddr1Between(String value1, String value2) {
            addCriterion("SHIPADDR1 between", value1, value2, "shipaddr1");
            return (Criteria) this;
        }

        public Criteria andShipaddr1NotBetween(String value1, String value2) {
            addCriterion("SHIPADDR1 not between", value1, value2, "shipaddr1");
            return (Criteria) this;
        }

        public Criteria andShipaddr2IsNull() {
            addCriterion("SHIPADDR2 is null");
            return (Criteria) this;
        }

        public Criteria andShipaddr2IsNotNull() {
            addCriterion("SHIPADDR2 is not null");
            return (Criteria) this;
        }

        public Criteria andShipaddr2EqualTo(String value) {
            addCriterion("SHIPADDR2 =", value, "shipaddr2");
            return (Criteria) this;
        }

        public Criteria andShipaddr2NotEqualTo(String value) {
            addCriterion("SHIPADDR2 <>", value, "shipaddr2");
            return (Criteria) this;
        }

        public Criteria andShipaddr2GreaterThan(String value) {
            addCriterion("SHIPADDR2 >", value, "shipaddr2");
            return (Criteria) this;
        }

        public Criteria andShipaddr2GreaterThanOrEqualTo(String value) {
            addCriterion("SHIPADDR2 >=", value, "shipaddr2");
            return (Criteria) this;
        }

        public Criteria andShipaddr2LessThan(String value) {
            addCriterion("SHIPADDR2 <", value, "shipaddr2");
            return (Criteria) this;
        }

        public Criteria andShipaddr2LessThanOrEqualTo(String value) {
            addCriterion("SHIPADDR2 <=", value, "shipaddr2");
            return (Criteria) this;
        }

        public Criteria andShipaddr2Like(String value) {
            addCriterion("SHIPADDR2 like", value, "shipaddr2");
            return (Criteria) this;
        }

        public Criteria andShipaddr2NotLike(String value) {
            addCriterion("SHIPADDR2 not like", value, "shipaddr2");
            return (Criteria) this;
        }

        public Criteria andShipaddr2In(List<String> values) {
            addCriterion("SHIPADDR2 in", values, "shipaddr2");
            return (Criteria) this;
        }

        public Criteria andShipaddr2NotIn(List<String> values) {
            addCriterion("SHIPADDR2 not in", values, "shipaddr2");
            return (Criteria) this;
        }

        public Criteria andShipaddr2Between(String value1, String value2) {
            addCriterion("SHIPADDR2 between", value1, value2, "shipaddr2");
            return (Criteria) this;
        }

        public Criteria andShipaddr2NotBetween(String value1, String value2) {
            addCriterion("SHIPADDR2 not between", value1, value2, "shipaddr2");
            return (Criteria) this;
        }

        public Criteria andShipcityIsNull() {
            addCriterion("SHIPCITY is null");
            return (Criteria) this;
        }

        public Criteria andShipcityIsNotNull() {
            addCriterion("SHIPCITY is not null");
            return (Criteria) this;
        }

        public Criteria andShipcityEqualTo(String value) {
            addCriterion("SHIPCITY =", value, "shipcity");
            return (Criteria) this;
        }

        public Criteria andShipcityNotEqualTo(String value) {
            addCriterion("SHIPCITY <>", value, "shipcity");
            return (Criteria) this;
        }

        public Criteria andShipcityGreaterThan(String value) {
            addCriterion("SHIPCITY >", value, "shipcity");
            return (Criteria) this;
        }

        public Criteria andShipcityGreaterThanOrEqualTo(String value) {
            addCriterion("SHIPCITY >=", value, "shipcity");
            return (Criteria) this;
        }

        public Criteria andShipcityLessThan(String value) {
            addCriterion("SHIPCITY <", value, "shipcity");
            return (Criteria) this;
        }

        public Criteria andShipcityLessThanOrEqualTo(String value) {
            addCriterion("SHIPCITY <=", value, "shipcity");
            return (Criteria) this;
        }

        public Criteria andShipcityLike(String value) {
            addCriterion("SHIPCITY like", value, "shipcity");
            return (Criteria) this;
        }

        public Criteria andShipcityNotLike(String value) {
            addCriterion("SHIPCITY not like", value, "shipcity");
            return (Criteria) this;
        }

        public Criteria andShipcityIn(List<String> values) {
            addCriterion("SHIPCITY in", values, "shipcity");
            return (Criteria) this;
        }

        public Criteria andShipcityNotIn(List<String> values) {
            addCriterion("SHIPCITY not in", values, "shipcity");
            return (Criteria) this;
        }

        public Criteria andShipcityBetween(String value1, String value2) {
            addCriterion("SHIPCITY between", value1, value2, "shipcity");
            return (Criteria) this;
        }

        public Criteria andShipcityNotBetween(String value1, String value2) {
            addCriterion("SHIPCITY not between", value1, value2, "shipcity");
            return (Criteria) this;
        }

        public Criteria andShipstateIsNull() {
            addCriterion("SHIPSTATE is null");
            return (Criteria) this;
        }

        public Criteria andShipstateIsNotNull() {
            addCriterion("SHIPSTATE is not null");
            return (Criteria) this;
        }

        public Criteria andShipstateEqualTo(String value) {
            addCriterion("SHIPSTATE =", value, "shipstate");
            return (Criteria) this;
        }

        public Criteria andShipstateNotEqualTo(String value) {
            addCriterion("SHIPSTATE <>", value, "shipstate");
            return (Criteria) this;
        }

        public Criteria andShipstateGreaterThan(String value) {
            addCriterion("SHIPSTATE >", value, "shipstate");
            return (Criteria) this;
        }

        public Criteria andShipstateGreaterThanOrEqualTo(String value) {
            addCriterion("SHIPSTATE >=", value, "shipstate");
            return (Criteria) this;
        }

        public Criteria andShipstateLessThan(String value) {
            addCriterion("SHIPSTATE <", value, "shipstate");
            return (Criteria) this;
        }

        public Criteria andShipstateLessThanOrEqualTo(String value) {
            addCriterion("SHIPSTATE <=", value, "shipstate");
            return (Criteria) this;
        }

        public Criteria andShipstateLike(String value) {
            addCriterion("SHIPSTATE like", value, "shipstate");
            return (Criteria) this;
        }

        public Criteria andShipstateNotLike(String value) {
            addCriterion("SHIPSTATE not like", value, "shipstate");
            return (Criteria) this;
        }

        public Criteria andShipstateIn(List<String> values) {
            addCriterion("SHIPSTATE in", values, "shipstate");
            return (Criteria) this;
        }

        public Criteria andShipstateNotIn(List<String> values) {
            addCriterion("SHIPSTATE not in", values, "shipstate");
            return (Criteria) this;
        }

        public Criteria andShipstateBetween(String value1, String value2) {
            addCriterion("SHIPSTATE between", value1, value2, "shipstate");
            return (Criteria) this;
        }

        public Criteria andShipstateNotBetween(String value1, String value2) {
            addCriterion("SHIPSTATE not between", value1, value2, "shipstate");
            return (Criteria) this;
        }

        public Criteria andShipzipIsNull() {
            addCriterion("SHIPZIP is null");
            return (Criteria) this;
        }

        public Criteria andShipzipIsNotNull() {
            addCriterion("SHIPZIP is not null");
            return (Criteria) this;
        }

        public Criteria andShipzipEqualTo(String value) {
            addCriterion("SHIPZIP =", value, "shipzip");
            return (Criteria) this;
        }

        public Criteria andShipzipNotEqualTo(String value) {
            addCriterion("SHIPZIP <>", value, "shipzip");
            return (Criteria) this;
        }

        public Criteria andShipzipGreaterThan(String value) {
            addCriterion("SHIPZIP >", value, "shipzip");
            return (Criteria) this;
        }

        public Criteria andShipzipGreaterThanOrEqualTo(String value) {
            addCriterion("SHIPZIP >=", value, "shipzip");
            return (Criteria) this;
        }

        public Criteria andShipzipLessThan(String value) {
            addCriterion("SHIPZIP <", value, "shipzip");
            return (Criteria) this;
        }

        public Criteria andShipzipLessThanOrEqualTo(String value) {
            addCriterion("SHIPZIP <=", value, "shipzip");
            return (Criteria) this;
        }

        public Criteria andShipzipLike(String value) {
            addCriterion("SHIPZIP like", value, "shipzip");
            return (Criteria) this;
        }

        public Criteria andShipzipNotLike(String value) {
            addCriterion("SHIPZIP not like", value, "shipzip");
            return (Criteria) this;
        }

        public Criteria andShipzipIn(List<String> values) {
            addCriterion("SHIPZIP in", values, "shipzip");
            return (Criteria) this;
        }

        public Criteria andShipzipNotIn(List<String> values) {
            addCriterion("SHIPZIP not in", values, "shipzip");
            return (Criteria) this;
        }

        public Criteria andShipzipBetween(String value1, String value2) {
            addCriterion("SHIPZIP between", value1, value2, "shipzip");
            return (Criteria) this;
        }

        public Criteria andShipzipNotBetween(String value1, String value2) {
            addCriterion("SHIPZIP not between", value1, value2, "shipzip");
            return (Criteria) this;
        }

        public Criteria andShipcountryIsNull() {
            addCriterion("SHIPCOUNTRY is null");
            return (Criteria) this;
        }

        public Criteria andShipcountryIsNotNull() {
            addCriterion("SHIPCOUNTRY is not null");
            return (Criteria) this;
        }

        public Criteria andShipcountryEqualTo(String value) {
            addCriterion("SHIPCOUNTRY =", value, "shipcountry");
            return (Criteria) this;
        }

        public Criteria andShipcountryNotEqualTo(String value) {
            addCriterion("SHIPCOUNTRY <>", value, "shipcountry");
            return (Criteria) this;
        }

        public Criteria andShipcountryGreaterThan(String value) {
            addCriterion("SHIPCOUNTRY >", value, "shipcountry");
            return (Criteria) this;
        }

        public Criteria andShipcountryGreaterThanOrEqualTo(String value) {
            addCriterion("SHIPCOUNTRY >=", value, "shipcountry");
            return (Criteria) this;
        }

        public Criteria andShipcountryLessThan(String value) {
            addCriterion("SHIPCOUNTRY <", value, "shipcountry");
            return (Criteria) this;
        }

        public Criteria andShipcountryLessThanOrEqualTo(String value) {
            addCriterion("SHIPCOUNTRY <=", value, "shipcountry");
            return (Criteria) this;
        }

        public Criteria andShipcountryLike(String value) {
            addCriterion("SHIPCOUNTRY like", value, "shipcountry");
            return (Criteria) this;
        }

        public Criteria andShipcountryNotLike(String value) {
            addCriterion("SHIPCOUNTRY not like", value, "shipcountry");
            return (Criteria) this;
        }

        public Criteria andShipcountryIn(List<String> values) {
            addCriterion("SHIPCOUNTRY in", values, "shipcountry");
            return (Criteria) this;
        }

        public Criteria andShipcountryNotIn(List<String> values) {
            addCriterion("SHIPCOUNTRY not in", values, "shipcountry");
            return (Criteria) this;
        }

        public Criteria andShipcountryBetween(String value1, String value2) {
            addCriterion("SHIPCOUNTRY between", value1, value2, "shipcountry");
            return (Criteria) this;
        }

        public Criteria andShipcountryNotBetween(String value1, String value2) {
            addCriterion("SHIPCOUNTRY not between", value1, value2, "shipcountry");
            return (Criteria) this;
        }

        public Criteria andBilladdr1IsNull() {
            addCriterion("BILLADDR1 is null");
            return (Criteria) this;
        }

        public Criteria andBilladdr1IsNotNull() {
            addCriterion("BILLADDR1 is not null");
            return (Criteria) this;
        }

        public Criteria andBilladdr1EqualTo(String value) {
            addCriterion("BILLADDR1 =", value, "billaddr1");
            return (Criteria) this;
        }

        public Criteria andBilladdr1NotEqualTo(String value) {
            addCriterion("BILLADDR1 <>", value, "billaddr1");
            return (Criteria) this;
        }

        public Criteria andBilladdr1GreaterThan(String value) {
            addCriterion("BILLADDR1 >", value, "billaddr1");
            return (Criteria) this;
        }

        public Criteria andBilladdr1GreaterThanOrEqualTo(String value) {
            addCriterion("BILLADDR1 >=", value, "billaddr1");
            return (Criteria) this;
        }

        public Criteria andBilladdr1LessThan(String value) {
            addCriterion("BILLADDR1 <", value, "billaddr1");
            return (Criteria) this;
        }

        public Criteria andBilladdr1LessThanOrEqualTo(String value) {
            addCriterion("BILLADDR1 <=", value, "billaddr1");
            return (Criteria) this;
        }

        public Criteria andBilladdr1Like(String value) {
            addCriterion("BILLADDR1 like", value, "billaddr1");
            return (Criteria) this;
        }

        public Criteria andBilladdr1NotLike(String value) {
            addCriterion("BILLADDR1 not like", value, "billaddr1");
            return (Criteria) this;
        }

        public Criteria andBilladdr1In(List<String> values) {
            addCriterion("BILLADDR1 in", values, "billaddr1");
            return (Criteria) this;
        }

        public Criteria andBilladdr1NotIn(List<String> values) {
            addCriterion("BILLADDR1 not in", values, "billaddr1");
            return (Criteria) this;
        }

        public Criteria andBilladdr1Between(String value1, String value2) {
            addCriterion("BILLADDR1 between", value1, value2, "billaddr1");
            return (Criteria) this;
        }

        public Criteria andBilladdr1NotBetween(String value1, String value2) {
            addCriterion("BILLADDR1 not between", value1, value2, "billaddr1");
            return (Criteria) this;
        }

        public Criteria andBilladdr2IsNull() {
            addCriterion("BILLADDR2 is null");
            return (Criteria) this;
        }

        public Criteria andBilladdr2IsNotNull() {
            addCriterion("BILLADDR2 is not null");
            return (Criteria) this;
        }

        public Criteria andBilladdr2EqualTo(String value) {
            addCriterion("BILLADDR2 =", value, "billaddr2");
            return (Criteria) this;
        }

        public Criteria andBilladdr2NotEqualTo(String value) {
            addCriterion("BILLADDR2 <>", value, "billaddr2");
            return (Criteria) this;
        }

        public Criteria andBilladdr2GreaterThan(String value) {
            addCriterion("BILLADDR2 >", value, "billaddr2");
            return (Criteria) this;
        }

        public Criteria andBilladdr2GreaterThanOrEqualTo(String value) {
            addCriterion("BILLADDR2 >=", value, "billaddr2");
            return (Criteria) this;
        }

        public Criteria andBilladdr2LessThan(String value) {
            addCriterion("BILLADDR2 <", value, "billaddr2");
            return (Criteria) this;
        }

        public Criteria andBilladdr2LessThanOrEqualTo(String value) {
            addCriterion("BILLADDR2 <=", value, "billaddr2");
            return (Criteria) this;
        }

        public Criteria andBilladdr2Like(String value) {
            addCriterion("BILLADDR2 like", value, "billaddr2");
            return (Criteria) this;
        }

        public Criteria andBilladdr2NotLike(String value) {
            addCriterion("BILLADDR2 not like", value, "billaddr2");
            return (Criteria) this;
        }

        public Criteria andBilladdr2In(List<String> values) {
            addCriterion("BILLADDR2 in", values, "billaddr2");
            return (Criteria) this;
        }

        public Criteria andBilladdr2NotIn(List<String> values) {
            addCriterion("BILLADDR2 not in", values, "billaddr2");
            return (Criteria) this;
        }

        public Criteria andBilladdr2Between(String value1, String value2) {
            addCriterion("BILLADDR2 between", value1, value2, "billaddr2");
            return (Criteria) this;
        }

        public Criteria andBilladdr2NotBetween(String value1, String value2) {
            addCriterion("BILLADDR2 not between", value1, value2, "billaddr2");
            return (Criteria) this;
        }

        public Criteria andBillcityIsNull() {
            addCriterion("BILLCITY is null");
            return (Criteria) this;
        }

        public Criteria andBillcityIsNotNull() {
            addCriterion("BILLCITY is not null");
            return (Criteria) this;
        }

        public Criteria andBillcityEqualTo(String value) {
            addCriterion("BILLCITY =", value, "billcity");
            return (Criteria) this;
        }

        public Criteria andBillcityNotEqualTo(String value) {
            addCriterion("BILLCITY <>", value, "billcity");
            return (Criteria) this;
        }

        public Criteria andBillcityGreaterThan(String value) {
            addCriterion("BILLCITY >", value, "billcity");
            return (Criteria) this;
        }

        public Criteria andBillcityGreaterThanOrEqualTo(String value) {
            addCriterion("BILLCITY >=", value, "billcity");
            return (Criteria) this;
        }

        public Criteria andBillcityLessThan(String value) {
            addCriterion("BILLCITY <", value, "billcity");
            return (Criteria) this;
        }

        public Criteria andBillcityLessThanOrEqualTo(String value) {
            addCriterion("BILLCITY <=", value, "billcity");
            return (Criteria) this;
        }

        public Criteria andBillcityLike(String value) {
            addCriterion("BILLCITY like", value, "billcity");
            return (Criteria) this;
        }

        public Criteria andBillcityNotLike(String value) {
            addCriterion("BILLCITY not like", value, "billcity");
            return (Criteria) this;
        }

        public Criteria andBillcityIn(List<String> values) {
            addCriterion("BILLCITY in", values, "billcity");
            return (Criteria) this;
        }

        public Criteria andBillcityNotIn(List<String> values) {
            addCriterion("BILLCITY not in", values, "billcity");
            return (Criteria) this;
        }

        public Criteria andBillcityBetween(String value1, String value2) {
            addCriterion("BILLCITY between", value1, value2, "billcity");
            return (Criteria) this;
        }

        public Criteria andBillcityNotBetween(String value1, String value2) {
            addCriterion("BILLCITY not between", value1, value2, "billcity");
            return (Criteria) this;
        }

        public Criteria andBillstateIsNull() {
            addCriterion("BILLSTATE is null");
            return (Criteria) this;
        }

        public Criteria andBillstateIsNotNull() {
            addCriterion("BILLSTATE is not null");
            return (Criteria) this;
        }

        public Criteria andBillstateEqualTo(String value) {
            addCriterion("BILLSTATE =", value, "billstate");
            return (Criteria) this;
        }

        public Criteria andBillstateNotEqualTo(String value) {
            addCriterion("BILLSTATE <>", value, "billstate");
            return (Criteria) this;
        }

        public Criteria andBillstateGreaterThan(String value) {
            addCriterion("BILLSTATE >", value, "billstate");
            return (Criteria) this;
        }

        public Criteria andBillstateGreaterThanOrEqualTo(String value) {
            addCriterion("BILLSTATE >=", value, "billstate");
            return (Criteria) this;
        }

        public Criteria andBillstateLessThan(String value) {
            addCriterion("BILLSTATE <", value, "billstate");
            return (Criteria) this;
        }

        public Criteria andBillstateLessThanOrEqualTo(String value) {
            addCriterion("BILLSTATE <=", value, "billstate");
            return (Criteria) this;
        }

        public Criteria andBillstateLike(String value) {
            addCriterion("BILLSTATE like", value, "billstate");
            return (Criteria) this;
        }

        public Criteria andBillstateNotLike(String value) {
            addCriterion("BILLSTATE not like", value, "billstate");
            return (Criteria) this;
        }

        public Criteria andBillstateIn(List<String> values) {
            addCriterion("BILLSTATE in", values, "billstate");
            return (Criteria) this;
        }

        public Criteria andBillstateNotIn(List<String> values) {
            addCriterion("BILLSTATE not in", values, "billstate");
            return (Criteria) this;
        }

        public Criteria andBillstateBetween(String value1, String value2) {
            addCriterion("BILLSTATE between", value1, value2, "billstate");
            return (Criteria) this;
        }

        public Criteria andBillstateNotBetween(String value1, String value2) {
            addCriterion("BILLSTATE not between", value1, value2, "billstate");
            return (Criteria) this;
        }

        public Criteria andBillzipIsNull() {
            addCriterion("BILLZIP is null");
            return (Criteria) this;
        }

        public Criteria andBillzipIsNotNull() {
            addCriterion("BILLZIP is not null");
            return (Criteria) this;
        }

        public Criteria andBillzipEqualTo(String value) {
            addCriterion("BILLZIP =", value, "billzip");
            return (Criteria) this;
        }

        public Criteria andBillzipNotEqualTo(String value) {
            addCriterion("BILLZIP <>", value, "billzip");
            return (Criteria) this;
        }

        public Criteria andBillzipGreaterThan(String value) {
            addCriterion("BILLZIP >", value, "billzip");
            return (Criteria) this;
        }

        public Criteria andBillzipGreaterThanOrEqualTo(String value) {
            addCriterion("BILLZIP >=", value, "billzip");
            return (Criteria) this;
        }

        public Criteria andBillzipLessThan(String value) {
            addCriterion("BILLZIP <", value, "billzip");
            return (Criteria) this;
        }

        public Criteria andBillzipLessThanOrEqualTo(String value) {
            addCriterion("BILLZIP <=", value, "billzip");
            return (Criteria) this;
        }

        public Criteria andBillzipLike(String value) {
            addCriterion("BILLZIP like", value, "billzip");
            return (Criteria) this;
        }

        public Criteria andBillzipNotLike(String value) {
            addCriterion("BILLZIP not like", value, "billzip");
            return (Criteria) this;
        }

        public Criteria andBillzipIn(List<String> values) {
            addCriterion("BILLZIP in", values, "billzip");
            return (Criteria) this;
        }

        public Criteria andBillzipNotIn(List<String> values) {
            addCriterion("BILLZIP not in", values, "billzip");
            return (Criteria) this;
        }

        public Criteria andBillzipBetween(String value1, String value2) {
            addCriterion("BILLZIP between", value1, value2, "billzip");
            return (Criteria) this;
        }

        public Criteria andBillzipNotBetween(String value1, String value2) {
            addCriterion("BILLZIP not between", value1, value2, "billzip");
            return (Criteria) this;
        }

        public Criteria andBillcountryIsNull() {
            addCriterion("BILLCOUNTRY is null");
            return (Criteria) this;
        }

        public Criteria andBillcountryIsNotNull() {
            addCriterion("BILLCOUNTRY is not null");
            return (Criteria) this;
        }

        public Criteria andBillcountryEqualTo(String value) {
            addCriterion("BILLCOUNTRY =", value, "billcountry");
            return (Criteria) this;
        }

        public Criteria andBillcountryNotEqualTo(String value) {
            addCriterion("BILLCOUNTRY <>", value, "billcountry");
            return (Criteria) this;
        }

        public Criteria andBillcountryGreaterThan(String value) {
            addCriterion("BILLCOUNTRY >", value, "billcountry");
            return (Criteria) this;
        }

        public Criteria andBillcountryGreaterThanOrEqualTo(String value) {
            addCriterion("BILLCOUNTRY >=", value, "billcountry");
            return (Criteria) this;
        }

        public Criteria andBillcountryLessThan(String value) {
            addCriterion("BILLCOUNTRY <", value, "billcountry");
            return (Criteria) this;
        }

        public Criteria andBillcountryLessThanOrEqualTo(String value) {
            addCriterion("BILLCOUNTRY <=", value, "billcountry");
            return (Criteria) this;
        }

        public Criteria andBillcountryLike(String value) {
            addCriterion("BILLCOUNTRY like", value, "billcountry");
            return (Criteria) this;
        }

        public Criteria andBillcountryNotLike(String value) {
            addCriterion("BILLCOUNTRY not like", value, "billcountry");
            return (Criteria) this;
        }

        public Criteria andBillcountryIn(List<String> values) {
            addCriterion("BILLCOUNTRY in", values, "billcountry");
            return (Criteria) this;
        }

        public Criteria andBillcountryNotIn(List<String> values) {
            addCriterion("BILLCOUNTRY not in", values, "billcountry");
            return (Criteria) this;
        }

        public Criteria andBillcountryBetween(String value1, String value2) {
            addCriterion("BILLCOUNTRY between", value1, value2, "billcountry");
            return (Criteria) this;
        }

        public Criteria andBillcountryNotBetween(String value1, String value2) {
            addCriterion("BILLCOUNTRY not between", value1, value2, "billcountry");
            return (Criteria) this;
        }

        public Criteria andCourierIsNull() {
            addCriterion("COURIER is null");
            return (Criteria) this;
        }

        public Criteria andCourierIsNotNull() {
            addCriterion("COURIER is not null");
            return (Criteria) this;
        }

        public Criteria andCourierEqualTo(String value) {
            addCriterion("COURIER =", value, "courier");
            return (Criteria) this;
        }

        public Criteria andCourierNotEqualTo(String value) {
            addCriterion("COURIER <>", value, "courier");
            return (Criteria) this;
        }

        public Criteria andCourierGreaterThan(String value) {
            addCriterion("COURIER >", value, "courier");
            return (Criteria) this;
        }

        public Criteria andCourierGreaterThanOrEqualTo(String value) {
            addCriterion("COURIER >=", value, "courier");
            return (Criteria) this;
        }

        public Criteria andCourierLessThan(String value) {
            addCriterion("COURIER <", value, "courier");
            return (Criteria) this;
        }

        public Criteria andCourierLessThanOrEqualTo(String value) {
            addCriterion("COURIER <=", value, "courier");
            return (Criteria) this;
        }

        public Criteria andCourierLike(String value) {
            addCriterion("COURIER like", value, "courier");
            return (Criteria) this;
        }

        public Criteria andCourierNotLike(String value) {
            addCriterion("COURIER not like", value, "courier");
            return (Criteria) this;
        }

        public Criteria andCourierIn(List<String> values) {
            addCriterion("COURIER in", values, "courier");
            return (Criteria) this;
        }

        public Criteria andCourierNotIn(List<String> values) {
            addCriterion("COURIER not in", values, "courier");
            return (Criteria) this;
        }

        public Criteria andCourierBetween(String value1, String value2) {
            addCriterion("COURIER between", value1, value2, "courier");
            return (Criteria) this;
        }

        public Criteria andCourierNotBetween(String value1, String value2) {
            addCriterion("COURIER not between", value1, value2, "courier");
            return (Criteria) this;
        }

        public Criteria andTotalpriceIsNull() {
            addCriterion("TOTALPRICE is null");
            return (Criteria) this;
        }

        public Criteria andTotalpriceIsNotNull() {
            addCriterion("TOTALPRICE is not null");
            return (Criteria) this;
        }

        public Criteria andTotalpriceEqualTo(BigDecimal value) {
            addCriterion("TOTALPRICE =", value, "totalprice");
            return (Criteria) this;
        }

        public Criteria andTotalpriceNotEqualTo(BigDecimal value) {
            addCriterion("TOTALPRICE <>", value, "totalprice");
            return (Criteria) this;
        }

        public Criteria andTotalpriceGreaterThan(BigDecimal value) {
            addCriterion("TOTALPRICE >", value, "totalprice");
            return (Criteria) this;
        }

        public Criteria andTotalpriceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("TOTALPRICE >=", value, "totalprice");
            return (Criteria) this;
        }

        public Criteria andTotalpriceLessThan(BigDecimal value) {
            addCriterion("TOTALPRICE <", value, "totalprice");
            return (Criteria) this;
        }

        public Criteria andTotalpriceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("TOTALPRICE <=", value, "totalprice");
            return (Criteria) this;
        }

        public Criteria andTotalpriceIn(List<BigDecimal> values) {
            addCriterion("TOTALPRICE in", values, "totalprice");
            return (Criteria) this;
        }

        public Criteria andTotalpriceNotIn(List<BigDecimal> values) {
            addCriterion("TOTALPRICE not in", values, "totalprice");
            return (Criteria) this;
        }

        public Criteria andTotalpriceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("TOTALPRICE between", value1, value2, "totalprice");
            return (Criteria) this;
        }

        public Criteria andTotalpriceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("TOTALPRICE not between", value1, value2, "totalprice");
            return (Criteria) this;
        }

        public Criteria andBilltofirstnameIsNull() {
            addCriterion("BILLTOFIRSTNAME is null");
            return (Criteria) this;
        }

        public Criteria andBilltofirstnameIsNotNull() {
            addCriterion("BILLTOFIRSTNAME is not null");
            return (Criteria) this;
        }

        public Criteria andBilltofirstnameEqualTo(String value) {
            addCriterion("BILLTOFIRSTNAME =", value, "billtofirstname");
            return (Criteria) this;
        }

        public Criteria andBilltofirstnameNotEqualTo(String value) {
            addCriterion("BILLTOFIRSTNAME <>", value, "billtofirstname");
            return (Criteria) this;
        }

        public Criteria andBilltofirstnameGreaterThan(String value) {
            addCriterion("BILLTOFIRSTNAME >", value, "billtofirstname");
            return (Criteria) this;
        }

        public Criteria andBilltofirstnameGreaterThanOrEqualTo(String value) {
            addCriterion("BILLTOFIRSTNAME >=", value, "billtofirstname");
            return (Criteria) this;
        }

        public Criteria andBilltofirstnameLessThan(String value) {
            addCriterion("BILLTOFIRSTNAME <", value, "billtofirstname");
            return (Criteria) this;
        }

        public Criteria andBilltofirstnameLessThanOrEqualTo(String value) {
            addCriterion("BILLTOFIRSTNAME <=", value, "billtofirstname");
            return (Criteria) this;
        }

        public Criteria andBilltofirstnameLike(String value) {
            addCriterion("BILLTOFIRSTNAME like", value, "billtofirstname");
            return (Criteria) this;
        }

        public Criteria andBilltofirstnameNotLike(String value) {
            addCriterion("BILLTOFIRSTNAME not like", value, "billtofirstname");
            return (Criteria) this;
        }

        public Criteria andBilltofirstnameIn(List<String> values) {
            addCriterion("BILLTOFIRSTNAME in", values, "billtofirstname");
            return (Criteria) this;
        }

        public Criteria andBilltofirstnameNotIn(List<String> values) {
            addCriterion("BILLTOFIRSTNAME not in", values, "billtofirstname");
            return (Criteria) this;
        }

        public Criteria andBilltofirstnameBetween(String value1, String value2) {
            addCriterion("BILLTOFIRSTNAME between", value1, value2, "billtofirstname");
            return (Criteria) this;
        }

        public Criteria andBilltofirstnameNotBetween(String value1, String value2) {
            addCriterion("BILLTOFIRSTNAME not between", value1, value2, "billtofirstname");
            return (Criteria) this;
        }

        public Criteria andBilltolastnameIsNull() {
            addCriterion("BILLTOLASTNAME is null");
            return (Criteria) this;
        }

        public Criteria andBilltolastnameIsNotNull() {
            addCriterion("BILLTOLASTNAME is not null");
            return (Criteria) this;
        }

        public Criteria andBilltolastnameEqualTo(String value) {
            addCriterion("BILLTOLASTNAME =", value, "billtolastname");
            return (Criteria) this;
        }

        public Criteria andBilltolastnameNotEqualTo(String value) {
            addCriterion("BILLTOLASTNAME <>", value, "billtolastname");
            return (Criteria) this;
        }

        public Criteria andBilltolastnameGreaterThan(String value) {
            addCriterion("BILLTOLASTNAME >", value, "billtolastname");
            return (Criteria) this;
        }

        public Criteria andBilltolastnameGreaterThanOrEqualTo(String value) {
            addCriterion("BILLTOLASTNAME >=", value, "billtolastname");
            return (Criteria) this;
        }

        public Criteria andBilltolastnameLessThan(String value) {
            addCriterion("BILLTOLASTNAME <", value, "billtolastname");
            return (Criteria) this;
        }

        public Criteria andBilltolastnameLessThanOrEqualTo(String value) {
            addCriterion("BILLTOLASTNAME <=", value, "billtolastname");
            return (Criteria) this;
        }

        public Criteria andBilltolastnameLike(String value) {
            addCriterion("BILLTOLASTNAME like", value, "billtolastname");
            return (Criteria) this;
        }

        public Criteria andBilltolastnameNotLike(String value) {
            addCriterion("BILLTOLASTNAME not like", value, "billtolastname");
            return (Criteria) this;
        }

        public Criteria andBilltolastnameIn(List<String> values) {
            addCriterion("BILLTOLASTNAME in", values, "billtolastname");
            return (Criteria) this;
        }

        public Criteria andBilltolastnameNotIn(List<String> values) {
            addCriterion("BILLTOLASTNAME not in", values, "billtolastname");
            return (Criteria) this;
        }

        public Criteria andBilltolastnameBetween(String value1, String value2) {
            addCriterion("BILLTOLASTNAME between", value1, value2, "billtolastname");
            return (Criteria) this;
        }

        public Criteria andBilltolastnameNotBetween(String value1, String value2) {
            addCriterion("BILLTOLASTNAME not between", value1, value2, "billtolastname");
            return (Criteria) this;
        }

        public Criteria andShiptofirstnameIsNull() {
            addCriterion("SHIPTOFIRSTNAME is null");
            return (Criteria) this;
        }

        public Criteria andShiptofirstnameIsNotNull() {
            addCriterion("SHIPTOFIRSTNAME is not null");
            return (Criteria) this;
        }

        public Criteria andShiptofirstnameEqualTo(String value) {
            addCriterion("SHIPTOFIRSTNAME =", value, "shiptofirstname");
            return (Criteria) this;
        }

        public Criteria andShiptofirstnameNotEqualTo(String value) {
            addCriterion("SHIPTOFIRSTNAME <>", value, "shiptofirstname");
            return (Criteria) this;
        }

        public Criteria andShiptofirstnameGreaterThan(String value) {
            addCriterion("SHIPTOFIRSTNAME >", value, "shiptofirstname");
            return (Criteria) this;
        }

        public Criteria andShiptofirstnameGreaterThanOrEqualTo(String value) {
            addCriterion("SHIPTOFIRSTNAME >=", value, "shiptofirstname");
            return (Criteria) this;
        }

        public Criteria andShiptofirstnameLessThan(String value) {
            addCriterion("SHIPTOFIRSTNAME <", value, "shiptofirstname");
            return (Criteria) this;
        }

        public Criteria andShiptofirstnameLessThanOrEqualTo(String value) {
            addCriterion("SHIPTOFIRSTNAME <=", value, "shiptofirstname");
            return (Criteria) this;
        }

        public Criteria andShiptofirstnameLike(String value) {
            addCriterion("SHIPTOFIRSTNAME like", value, "shiptofirstname");
            return (Criteria) this;
        }

        public Criteria andShiptofirstnameNotLike(String value) {
            addCriterion("SHIPTOFIRSTNAME not like", value, "shiptofirstname");
            return (Criteria) this;
        }

        public Criteria andShiptofirstnameIn(List<String> values) {
            addCriterion("SHIPTOFIRSTNAME in", values, "shiptofirstname");
            return (Criteria) this;
        }

        public Criteria andShiptofirstnameNotIn(List<String> values) {
            addCriterion("SHIPTOFIRSTNAME not in", values, "shiptofirstname");
            return (Criteria) this;
        }

        public Criteria andShiptofirstnameBetween(String value1, String value2) {
            addCriterion("SHIPTOFIRSTNAME between", value1, value2, "shiptofirstname");
            return (Criteria) this;
        }

        public Criteria andShiptofirstnameNotBetween(String value1, String value2) {
            addCriterion("SHIPTOFIRSTNAME not between", value1, value2, "shiptofirstname");
            return (Criteria) this;
        }

        public Criteria andShiptolastnameIsNull() {
            addCriterion("SHIPTOLASTNAME is null");
            return (Criteria) this;
        }

        public Criteria andShiptolastnameIsNotNull() {
            addCriterion("SHIPTOLASTNAME is not null");
            return (Criteria) this;
        }

        public Criteria andShiptolastnameEqualTo(String value) {
            addCriterion("SHIPTOLASTNAME =", value, "shiptolastname");
            return (Criteria) this;
        }

        public Criteria andShiptolastnameNotEqualTo(String value) {
            addCriterion("SHIPTOLASTNAME <>", value, "shiptolastname");
            return (Criteria) this;
        }

        public Criteria andShiptolastnameGreaterThan(String value) {
            addCriterion("SHIPTOLASTNAME >", value, "shiptolastname");
            return (Criteria) this;
        }

        public Criteria andShiptolastnameGreaterThanOrEqualTo(String value) {
            addCriterion("SHIPTOLASTNAME >=", value, "shiptolastname");
            return (Criteria) this;
        }

        public Criteria andShiptolastnameLessThan(String value) {
            addCriterion("SHIPTOLASTNAME <", value, "shiptolastname");
            return (Criteria) this;
        }

        public Criteria andShiptolastnameLessThanOrEqualTo(String value) {
            addCriterion("SHIPTOLASTNAME <=", value, "shiptolastname");
            return (Criteria) this;
        }

        public Criteria andShiptolastnameLike(String value) {
            addCriterion("SHIPTOLASTNAME like", value, "shiptolastname");
            return (Criteria) this;
        }

        public Criteria andShiptolastnameNotLike(String value) {
            addCriterion("SHIPTOLASTNAME not like", value, "shiptolastname");
            return (Criteria) this;
        }

        public Criteria andShiptolastnameIn(List<String> values) {
            addCriterion("SHIPTOLASTNAME in", values, "shiptolastname");
            return (Criteria) this;
        }

        public Criteria andShiptolastnameNotIn(List<String> values) {
            addCriterion("SHIPTOLASTNAME not in", values, "shiptolastname");
            return (Criteria) this;
        }

        public Criteria andShiptolastnameBetween(String value1, String value2) {
            addCriterion("SHIPTOLASTNAME between", value1, value2, "shiptolastname");
            return (Criteria) this;
        }

        public Criteria andShiptolastnameNotBetween(String value1, String value2) {
            addCriterion("SHIPTOLASTNAME not between", value1, value2, "shiptolastname");
            return (Criteria) this;
        }

        public Criteria andCreditcardIsNull() {
            addCriterion("CREDITCARD is null");
            return (Criteria) this;
        }

        public Criteria andCreditcardIsNotNull() {
            addCriterion("CREDITCARD is not null");
            return (Criteria) this;
        }

        public Criteria andCreditcardEqualTo(String value) {
            addCriterion("CREDITCARD =", value, "creditcard");
            return (Criteria) this;
        }

        public Criteria andCreditcardNotEqualTo(String value) {
            addCriterion("CREDITCARD <>", value, "creditcard");
            return (Criteria) this;
        }

        public Criteria andCreditcardGreaterThan(String value) {
            addCriterion("CREDITCARD >", value, "creditcard");
            return (Criteria) this;
        }

        public Criteria andCreditcardGreaterThanOrEqualTo(String value) {
            addCriterion("CREDITCARD >=", value, "creditcard");
            return (Criteria) this;
        }

        public Criteria andCreditcardLessThan(String value) {
            addCriterion("CREDITCARD <", value, "creditcard");
            return (Criteria) this;
        }

        public Criteria andCreditcardLessThanOrEqualTo(String value) {
            addCriterion("CREDITCARD <=", value, "creditcard");
            return (Criteria) this;
        }

        public Criteria andCreditcardLike(String value) {
            addCriterion("CREDITCARD like", value, "creditcard");
            return (Criteria) this;
        }

        public Criteria andCreditcardNotLike(String value) {
            addCriterion("CREDITCARD not like", value, "creditcard");
            return (Criteria) this;
        }

        public Criteria andCreditcardIn(List<String> values) {
            addCriterion("CREDITCARD in", values, "creditcard");
            return (Criteria) this;
        }

        public Criteria andCreditcardNotIn(List<String> values) {
            addCriterion("CREDITCARD not in", values, "creditcard");
            return (Criteria) this;
        }

        public Criteria andCreditcardBetween(String value1, String value2) {
            addCriterion("CREDITCARD between", value1, value2, "creditcard");
            return (Criteria) this;
        }

        public Criteria andCreditcardNotBetween(String value1, String value2) {
            addCriterion("CREDITCARD not between", value1, value2, "creditcard");
            return (Criteria) this;
        }

        public Criteria andExprdateIsNull() {
            addCriterion("EXPRDATE is null");
            return (Criteria) this;
        }

        public Criteria andExprdateIsNotNull() {
            addCriterion("EXPRDATE is not null");
            return (Criteria) this;
        }

        public Criteria andExprdateEqualTo(String value) {
            addCriterion("EXPRDATE =", value, "exprdate");
            return (Criteria) this;
        }

        public Criteria andExprdateNotEqualTo(String value) {
            addCriterion("EXPRDATE <>", value, "exprdate");
            return (Criteria) this;
        }

        public Criteria andExprdateGreaterThan(String value) {
            addCriterion("EXPRDATE >", value, "exprdate");
            return (Criteria) this;
        }

        public Criteria andExprdateGreaterThanOrEqualTo(String value) {
            addCriterion("EXPRDATE >=", value, "exprdate");
            return (Criteria) this;
        }

        public Criteria andExprdateLessThan(String value) {
            addCriterion("EXPRDATE <", value, "exprdate");
            return (Criteria) this;
        }

        public Criteria andExprdateLessThanOrEqualTo(String value) {
            addCriterion("EXPRDATE <=", value, "exprdate");
            return (Criteria) this;
        }

        public Criteria andExprdateLike(String value) {
            addCriterion("EXPRDATE like", value, "exprdate");
            return (Criteria) this;
        }

        public Criteria andExprdateNotLike(String value) {
            addCriterion("EXPRDATE not like", value, "exprdate");
            return (Criteria) this;
        }

        public Criteria andExprdateIn(List<String> values) {
            addCriterion("EXPRDATE in", values, "exprdate");
            return (Criteria) this;
        }

        public Criteria andExprdateNotIn(List<String> values) {
            addCriterion("EXPRDATE not in", values, "exprdate");
            return (Criteria) this;
        }

        public Criteria andExprdateBetween(String value1, String value2) {
            addCriterion("EXPRDATE between", value1, value2, "exprdate");
            return (Criteria) this;
        }

        public Criteria andExprdateNotBetween(String value1, String value2) {
            addCriterion("EXPRDATE not between", value1, value2, "exprdate");
            return (Criteria) this;
        }

        public Criteria andCardtypeIsNull() {
            addCriterion("CARDTYPE is null");
            return (Criteria) this;
        }

        public Criteria andCardtypeIsNotNull() {
            addCriterion("CARDTYPE is not null");
            return (Criteria) this;
        }

        public Criteria andCardtypeEqualTo(String value) {
            addCriterion("CARDTYPE =", value, "cardtype");
            return (Criteria) this;
        }

        public Criteria andCardtypeNotEqualTo(String value) {
            addCriterion("CARDTYPE <>", value, "cardtype");
            return (Criteria) this;
        }

        public Criteria andCardtypeGreaterThan(String value) {
            addCriterion("CARDTYPE >", value, "cardtype");
            return (Criteria) this;
        }

        public Criteria andCardtypeGreaterThanOrEqualTo(String value) {
            addCriterion("CARDTYPE >=", value, "cardtype");
            return (Criteria) this;
        }

        public Criteria andCardtypeLessThan(String value) {
            addCriterion("CARDTYPE <", value, "cardtype");
            return (Criteria) this;
        }

        public Criteria andCardtypeLessThanOrEqualTo(String value) {
            addCriterion("CARDTYPE <=", value, "cardtype");
            return (Criteria) this;
        }

        public Criteria andCardtypeLike(String value) {
            addCriterion("CARDTYPE like", value, "cardtype");
            return (Criteria) this;
        }

        public Criteria andCardtypeNotLike(String value) {
            addCriterion("CARDTYPE not like", value, "cardtype");
            return (Criteria) this;
        }

        public Criteria andCardtypeIn(List<String> values) {
            addCriterion("CARDTYPE in", values, "cardtype");
            return (Criteria) this;
        }

        public Criteria andCardtypeNotIn(List<String> values) {
            addCriterion("CARDTYPE not in", values, "cardtype");
            return (Criteria) this;
        }

        public Criteria andCardtypeBetween(String value1, String value2) {
            addCriterion("CARDTYPE between", value1, value2, "cardtype");
            return (Criteria) this;
        }

        public Criteria andCardtypeNotBetween(String value1, String value2) {
            addCriterion("CARDTYPE not between", value1, value2, "cardtype");
            return (Criteria) this;
        }

        public Criteria andLocaleIsNull() {
            addCriterion("`LOCALE` is null");
            return (Criteria) this;
        }

        public Criteria andLocaleIsNotNull() {
            addCriterion("`LOCALE` is not null");
            return (Criteria) this;
        }

        public Criteria andLocaleEqualTo(String value) {
            addCriterion("`LOCALE` =", value, "locale");
            return (Criteria) this;
        }

        public Criteria andLocaleNotEqualTo(String value) {
            addCriterion("`LOCALE` <>", value, "locale");
            return (Criteria) this;
        }

        public Criteria andLocaleGreaterThan(String value) {
            addCriterion("`LOCALE` >", value, "locale");
            return (Criteria) this;
        }

        public Criteria andLocaleGreaterThanOrEqualTo(String value) {
            addCriterion("`LOCALE` >=", value, "locale");
            return (Criteria) this;
        }

        public Criteria andLocaleLessThan(String value) {
            addCriterion("`LOCALE` <", value, "locale");
            return (Criteria) this;
        }

        public Criteria andLocaleLessThanOrEqualTo(String value) {
            addCriterion("`LOCALE` <=", value, "locale");
            return (Criteria) this;
        }

        public Criteria andLocaleLike(String value) {
            addCriterion("`LOCALE` like", value, "locale");
            return (Criteria) this;
        }

        public Criteria andLocaleNotLike(String value) {
            addCriterion("`LOCALE` not like", value, "locale");
            return (Criteria) this;
        }

        public Criteria andLocaleIn(List<String> values) {
            addCriterion("`LOCALE` in", values, "locale");
            return (Criteria) this;
        }

        public Criteria andLocaleNotIn(List<String> values) {
            addCriterion("`LOCALE` not in", values, "locale");
            return (Criteria) this;
        }

        public Criteria andLocaleBetween(String value1, String value2) {
            addCriterion("`LOCALE` between", value1, value2, "locale");
            return (Criteria) this;
        }

        public Criteria andLocaleNotBetween(String value1, String value2) {
            addCriterion("`LOCALE` not between", value1, value2, "locale");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ORDERS
     *
     * @mbg.generated do_not_delete_during_merge Mon Apr 10 18:49:55 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ORDERS
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}