package com.github.zackwoo.scaffolding.entity;

import java.util.Date;

public class Orderstatus extends OrderstatusKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDERSTATUS.TIMESTAMP
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    private Date timestamp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDERSTATUS.STATUS
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    private String status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDERSTATUS.TIMESTAMP
     *
     * @return the value of ORDERSTATUS.TIMESTAMP
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    public Date getTimestamp() {
        return timestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDERSTATUS.TIMESTAMP
     *
     * @param timestamp the value for ORDERSTATUS.TIMESTAMP
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    public void setTimestamp(Date timestamp) {
        this.timestamp = timestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDERSTATUS.STATUS
     *
     * @return the value of ORDERSTATUS.STATUS
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDERSTATUS.STATUS
     *
     * @param status the value for ORDERSTATUS.STATUS
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }
}