package com.github.zackwoo.scaffolding.entity;

public class Product {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT.PRODUCTID
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    private String productid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT.CATEGORY
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    private String category;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT.NAME
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT.DESCN
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    private String descn;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRODUCT.PRODUCTID
     *
     * @return the value of PRODUCT.PRODUCTID
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    public String getProductid() {
        return productid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRODUCT.PRODUCTID
     *
     * @param productid the value for PRODUCT.PRODUCTID
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    public void setProductid(String productid) {
        this.productid = productid == null ? null : productid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRODUCT.CATEGORY
     *
     * @return the value of PRODUCT.CATEGORY
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    public String getCategory() {
        return category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRODUCT.CATEGORY
     *
     * @param category the value for PRODUCT.CATEGORY
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    public void setCategory(String category) {
        this.category = category == null ? null : category.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRODUCT.NAME
     *
     * @return the value of PRODUCT.NAME
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRODUCT.NAME
     *
     * @param name the value for PRODUCT.NAME
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRODUCT.DESCN
     *
     * @return the value of PRODUCT.DESCN
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    public String getDescn() {
        return descn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRODUCT.DESCN
     *
     * @param descn the value for PRODUCT.DESCN
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    public void setDescn(String descn) {
        this.descn = descn == null ? null : descn.trim();
    }
}