package com.github.zackwoo.scaffolding.entity;

public class Profile {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PROFILE.USERID
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    private String userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PROFILE.LANGPREF
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    private String langpref;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PROFILE.FAVCATEGORY
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    private String favcategory;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PROFILE.MYLISTOPT
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    private Integer mylistopt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PROFILE.BANNEROPT
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    private Integer banneropt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PROFILE.USERID
     *
     * @return the value of PROFILE.USERID
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PROFILE.USERID
     *
     * @param userid the value for PROFILE.USERID
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    public void setUserid(String userid) {
        this.userid = userid == null ? null : userid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PROFILE.LANGPREF
     *
     * @return the value of PROFILE.LANGPREF
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    public String getLangpref() {
        return langpref;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PROFILE.LANGPREF
     *
     * @param langpref the value for PROFILE.LANGPREF
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    public void setLangpref(String langpref) {
        this.langpref = langpref == null ? null : langpref.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PROFILE.FAVCATEGORY
     *
     * @return the value of PROFILE.FAVCATEGORY
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    public String getFavcategory() {
        return favcategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PROFILE.FAVCATEGORY
     *
     * @param favcategory the value for PROFILE.FAVCATEGORY
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    public void setFavcategory(String favcategory) {
        this.favcategory = favcategory == null ? null : favcategory.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PROFILE.MYLISTOPT
     *
     * @return the value of PROFILE.MYLISTOPT
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    public Integer getMylistopt() {
        return mylistopt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PROFILE.MYLISTOPT
     *
     * @param mylistopt the value for PROFILE.MYLISTOPT
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    public void setMylistopt(Integer mylistopt) {
        this.mylistopt = mylistopt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PROFILE.BANNEROPT
     *
     * @return the value of PROFILE.BANNEROPT
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    public Integer getBanneropt() {
        return banneropt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PROFILE.BANNEROPT
     *
     * @param banneropt the value for PROFILE.BANNEROPT
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    public void setBanneropt(Integer banneropt) {
        this.banneropt = banneropt;
    }
}