package com.github.zackwoo.scaffolding.entity;

public class Sequence {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SEQUENCE.NAME
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SEQUENCE.NEXTID
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    private Integer nextid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SEQUENCE.NAME
     *
     * @return the value of SEQUENCE.NAME
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SEQUENCE.NAME
     *
     * @param name the value for SEQUENCE.NAME
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SEQUENCE.NEXTID
     *
     * @return the value of SEQUENCE.NEXTID
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    public Integer getNextid() {
        return nextid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SEQUENCE.NEXTID
     *
     * @param nextid the value for SEQUENCE.NEXTID
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    public void setNextid(Integer nextid) {
        this.nextid = nextid;
    }
}