package com.github.zackwoo.scaffolding.entity;

public class Signon {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SIGNON.USERNAME
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SIGNON.PASSWORD
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    private String password;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SIGNON.USERNAME
     *
     * @return the value of SIGNON.USERNAME
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SIGNON.USERNAME
     *
     * @param username the value for SIGNON.USERNAME
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SIGNON.PASSWORD
     *
     * @return the value of SIGNON.PASSWORD
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SIGNON.PASSWORD
     *
     * @param password the value for SIGNON.PASSWORD
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }
}