package com.github.zackwoo.scaffolding.entity;

public class Supplier {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SUPPLIER.SUPPID
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    private Integer suppid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SUPPLIER.NAME
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SUPPLIER.STATUS
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SUPPLIER.ADDR1
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    private String addr1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SUPPLIER.ADDR2
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    private String addr2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SUPPLIER.CITY
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    private String city;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SUPPLIER.STATE
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    private String state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SUPPLIER.ZIP
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    private String zip;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SUPPLIER.PHONE
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    private String phone;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SUPPLIER.SUPPID
     *
     * @return the value of SUPPLIER.SUPPID
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    public Integer getSuppid() {
        return suppid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SUPPLIER.SUPPID
     *
     * @param suppid the value for SUPPLIER.SUPPID
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    public void setSuppid(Integer suppid) {
        this.suppid = suppid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SUPPLIER.NAME
     *
     * @return the value of SUPPLIER.NAME
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SUPPLIER.NAME
     *
     * @param name the value for SUPPLIER.NAME
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SUPPLIER.STATUS
     *
     * @return the value of SUPPLIER.STATUS
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SUPPLIER.STATUS
     *
     * @param status the value for SUPPLIER.STATUS
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SUPPLIER.ADDR1
     *
     * @return the value of SUPPLIER.ADDR1
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    public String getAddr1() {
        return addr1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SUPPLIER.ADDR1
     *
     * @param addr1 the value for SUPPLIER.ADDR1
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    public void setAddr1(String addr1) {
        this.addr1 = addr1 == null ? null : addr1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SUPPLIER.ADDR2
     *
     * @return the value of SUPPLIER.ADDR2
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    public String getAddr2() {
        return addr2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SUPPLIER.ADDR2
     *
     * @param addr2 the value for SUPPLIER.ADDR2
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    public void setAddr2(String addr2) {
        this.addr2 = addr2 == null ? null : addr2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SUPPLIER.CITY
     *
     * @return the value of SUPPLIER.CITY
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SUPPLIER.CITY
     *
     * @param city the value for SUPPLIER.CITY
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SUPPLIER.STATE
     *
     * @return the value of SUPPLIER.STATE
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SUPPLIER.STATE
     *
     * @param state the value for SUPPLIER.STATE
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SUPPLIER.ZIP
     *
     * @return the value of SUPPLIER.ZIP
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    public String getZip() {
        return zip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SUPPLIER.ZIP
     *
     * @param zip the value for SUPPLIER.ZIP
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    public void setZip(String zip) {
        this.zip = zip == null ? null : zip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SUPPLIER.PHONE
     *
     * @return the value of SUPPLIER.PHONE
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SUPPLIER.PHONE
     *
     * @param phone the value for SUPPLIER.PHONE
     *
     * @mbg.generated Mon Apr 10 18:49:55 CST 2017
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }
}